JuliaPackaging/BinaryBuilder.jl

REQUIRE
src/Auditor.jl
src/BinaryBuilder.jl
src/Dependency.jl
src/DockerRunner.jl
test/build_libfoo_tarballs.jl
test/runtests.jl

Since BinaryProvider recently made the same change.

Use `Platform`s instead of `Symbol`s to represent platforms

---

REQUIRE
appveyor.yml

We weren't even testing on 0.5 on Travis here.
FemtoCleaner should hopefully clean up after this. Hopefully...

Drop 0.5 support

---

src/Wizard.jl

"Conjuring binary elves since 2017"
Ok, I've now officially spent far too long on this :-)
I did some more fiddling to make the layout a bit better than the version I posted on slack.  Happy to change it a bit more, or change the embedded text to something more explanatory if you've got suggestions.

Binzard logo, as seen on slack

---

src/Wizard.jl

Use arch() instead of .arch

---

REQUIRE
src/Wizard.jl

Works fine, though deployment from travis to github is failing: https://travis-ci.org/Keno/IConvBuilder/builds/306624669
I might be doing the encryption wrong.

Add automatic creation of GitHub repositories

---

src/wizard/obtain_source.jl

Also try to look up refspecs in origin

---

.travis.yml
src/AutoBuild.jl
test/build_tests/libfoo/Makefile
test/runtests.jl

Fix and add tests for autobuild from git

---

deps/sandbox.c

We need to be more strict than the parent mount here. We could try to find out what those flags are, or we could just unconditionally be strict, since we don't need either of these options. The latter is simpler.

Mount shards as nodev nosuid

---

src/BinaryBuilder.jl
src/RootFS.jl
src/Runner.jl
src/UserNSRunner.jl

This requires the latest master of `BinaryProvider`.

Auto-detect the necessity of privileged mode on Arch

---

src/Auditor.jl

This fixes the issue that without this, full paths to things like `libgfortran` don't work.  :(

Automatically relink `libgfortran` to `@rpath/libgfortran` on OSX.

---

src/wizard/obtain_source.jl

Supersedes https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/142

Small cleanup to canonicalization routines

---

src/Auditor.jl

Fixes https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/140

Warn the user if `.dll` files exist within `$prefix/lib`

---

docs/make.jl

This is how my ``make.jl`` files look like for projects where the docs build on travis and everything works.

Fix doc deployment

---

src/AutoBuild.jl
src/wizard/deploy.jl
src/wizard/utils.jl

Small fixes, but closes https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/144

Better `build.jl` and `build_tarballs.jl` generation

---

src/AutoBuild.jl
src/wizard/deploy.jl

This allows us to shard our build across multiple Travis CI jobs, yet still have a single, monolothic `build.jl` in the end.  It also ends up cleaning up the `print_buildjl()` stuff a bit, although there's still work to do there.
We also  spice up the autogenerated `build.jl` significantly, adding in `--verbose` and `--only-buildjl` flags, etc...
This relies on https://github.com/JuliaPackaging/BinaryProvider.jl/pull/39

Add ability to reconstruct `build.jl` files from a GitHub releases page

---

src/AutoBuild.jl
src/wizard/deploy.jl
test/runtests.jl

Add test so this doesn't happen again

Fix incorrect url downloading in `product_hashes_from_github_release()`

---

src/auditor/dynamic_linkage.jl

https://travis-ci.org/visr/PROJBuilder/jobs/357843424#L529-L546
Related to rework in https://github.com/JuliaPackaging/BinaryProvider.jl/pull/50

Fix "Unsupported architecture 'ppc64le' for Linux"

---

src/Auditor.jl

When loading `.so` files that use LLVM, oftentimes internal LLVM
functions are called within the initialization routines of the `.so`
files.  This can cause Julia to segfault, which is bad.  Let's allow it
to continue segfaulting, but do so in an insulated Julia process so that
we don't end up killing ourselves during our audit phase.

Insulate `dlopen()` during auditing

---

src/AutoBuild.jl
test/runtests.jl

With this change, you are now able to use source listings such as the following:
```
sources = [
"https://github.com/.../foo.tar.gz" => "11aa33bb55dd...",
"local_patches",
]
```
`BinaryBuilder.jl` will automatically package up the local directory as a tarball and unpack it into your workspace.

Add ability to include local directories (e.g. patches)

---

src/auditor/dynamic_linkage.jl

As suggested by @staticfloat in #206

ignore libstdc++.6.dylib and  libstdc++.so.6

---

src/AutoBuild.jl
src/wizard/deploy.jl

Closes https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/224

Add `--help` to `build_tarballs()`

---

src/Wizard.jl

Ask the user if they want to resume the previous build if the last wizard state feels incomplete.
Closes https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/222

Save Wizard state to a global variable within `catch` block

---

REQUIRE
src/wizard/deploy.jl

Fixes https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/242

Use `HTTP.payload()` instead of `HTTP.load()`

---

deps/sandbox.c

@staticfloat, we'll need a new base rootfs with this fix.

Fix typos in 9p mounting code

---

.travis.yml
deps/sandbox.c
docs/src/environment_variables.md
src/Auditor.jl
src/AutoBuild.jl
src/BinaryBuilder.jl
src/Dependency.jl
src/QemuRunner.jl
src/RootFS.jl
src/Runner.jl
src/UserNSRunner.jl
src/wizard/interactive_build.jl
src/wizard/utils.jl
test/build_tests/interactive_tests/debug_test.jl
test/runtests.jl

Add `--debug` and cache downloads better

---

.travis.yml
deps/sandbox.c
src/QemuRunner.jl

Fixes #180. With this patchset, I am able to successfully have QemuBuilder run on OS X (it git clones a bunch of dependencies during the build process).

Give the Qemu runner access to the network

---

src/RootFS.jl

@Keno here's a new rootfs, once you push your changes to `sandbox.c` for network code, I'll update the `base` shard, update the hashes here, and merge this.

Bump rootfs version

---

.travis.yml
REQUIRE
src/Auditor.jl
src/Dependency.jl
src/RootFS.jl
src/Runner.jl
src/auditor/dynamic_linkage.jl
src/wizard/deploy.jl
src/wizard/interactive_build.jl
src/wizard/utils.jl
test/build_libfoo_tarballs.jl
test/build_tests/libfoo/Makefile
test/runtests.jl

This should set us up for better behavior with regards to file descriptor exhaustion.

readmeta rework

---

src/Auditor.jl
src/wizard/deploy.jl
src/wizard/obtain_source.jl
src/wizard/state.jl
test/wizard.jl

Depends on https://github.com/JuliaWeb/GitHub.jl/pull/112

Test GitHub deploy

---

docker_images/v0.6/Dockerfile
docs/src/environment_variables.md
src/BinaryBuilder.jl
src/RootFS.jl

This is helpful for dockerized builds

allow setting of ccache path directory

---

src/AutoBuild.jl

Mostly to be compatible with GitLab CI

Much more intelligent deployment information gathering

---

src/AutoBuild.jl
src/RootFS.jl
test/runtests.jl

Also expand test coverage to include this section so we don't break it again.

Fix errors when reconstructing build.jl files

---

src/auditor/dynamic_linkage.jl

This should fix https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/289

Eliminate `$ORIGIN` on Linux/FreeBSD

---

src/Auditor.jl
test/runtests.jl

:one: :zero: :package: -> :snake: -> :airplane:

Eliminate snakes from codebase

---

deps/sandbox.c
src/UserNSRunner.jl

To make julia tests pass inside the sandbox.
Also allow IOStream in run_interactive.

 Also bindmount /dev/tty

---

src/wizard/obtain_source.jl

We need to `collect()` before a bunch of these.

Fix `set` problems

---

src/Auditor.jl
src/Runner.jl

@SimonDanisch Here you go, this should fix your LibPngBuilder issues.

Fix LD_LIBRARY_PATH bug and windows symlink materialization bug

---

src/Runner.jl

This should solve more OSX C++ problems.

Must sneak `-stdlib=libc++` in on OSX `$CXX`

---

src/UserNSRunner.jl

This will avoid users trying to run BB on their old Linux systems and being disappointed when it errors out mysteriously in the middle of a `clone()` syscall or something.

Add kernel version check for UserNSRunner

---

src/Runner.jl

See https://github.com/bicycle1885/ZlibBuilder/pull/14#issuecomment-497628609

Add $prefix/share/pkgconfig to PKG_CONFIG_PATH

---

src/auditor/compiler_abi.jl

Change message to reference platforms not products

---

docs/src/FAQ.md
docs/src/build_tips.md
docs/src/environment_variables.md

There are some interesting tricks that I learnt on the Slack, but given its ephemeral nature I'd like to make this information more persistent, and useful for other people too.

Improve documentation

---

src/Prefix.jl
test/basic.jl

Also add a bunch more tests. I love large green numbers!

Fix directory symlinks in `symlink_tree()`

---

src/Runner.jl

This should fix the failure in https://github.com/JuliaPackaging/Yggdrasil/pull/195

Properly JIT windows tool wrappers

---

docker_images/v1.3/Dockerfile
src/AutoBuild.jl
src/BinaryBuilder.jl
src/Declarative.jl
src/Products.jl
src/Wizard.jl
test/declarative.jl

This pushes the separated registration work forward

Separated registration

---

src/AutoBuild.jl

We're going to get this registration thing right!

Split out JLL package initialization as well

---

src/AutoBuild.jl

Initialise LIBPATH_list with the libraries provided by Julia

---

src/wizard/deploy.jl

_Should_ fix #522, I didn't test (yet?)

Fix opening of PR to Yggdrasil

---

src/UserNSRunner.jl

We basically need to check that `--map` and `--workspace` work on the
current kernel.  It might be necessary for us to check squashfs and
unpacked separately in the future.

Improve `probe_unprivileged_containers()` to check mounting

---

Manifest.toml
Project.toml
src/AutoBuild.jl

Fixes https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/472

License JLL packages themselves as MIT

---

Project.toml

I hope I didn't miss any package.  This should allow auto-merge of https://github.com/JuliaRegistries/General/pull/6355

Put upper bounds to compat of dependencies

---

src/wizard/deploy.jl

Print PackageSpec correctly when printing build_tarball.jl from the wizard.
Produces
```
dependencies = [
PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95")
]
```
instead of
```
dependencies = [
"PackageSpec(
name = OpenSSL_jll
uuid = 458c3c95-2e84-50aa-8efc-19380b2a3a95
version = *
)",
]
```

Print PackageSpec correctly when printing build_tarball.jl

---

src/Wizard.jl
src/wizard/github.jl

Fix https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/566

Use different note when obtain GitHub token

---

Artifacts.toml
src/Rootfs.jl

Add GCC v9 shard

---

Artifacts.toml

This includes Valentine and Keno's use-after-free patch.

Bump LLVM shards

---

Artifacts.toml
src/Rootfs.jl

This should fix Jacob's cmake woes

Bump `PlatformSupport` to fix `cmake` trying to use `gcc-ar` instead of `ar`

---

src/Auditor.jl
src/auditor/dynamic_linkage.jl

Add audit check about troublesome libraries

---

Manifest.toml
src/wizard/utils.jl

We may finally be able to use BB on 1.4+ again

Upgrade dependencies, add compatibility for Julia 1.4+

---

src/auditor/compiler_abi.jl

Ref https://github.com/JuliaPackaging/BinaryBuilder.jl/commit/491e6ccd723aa2c864b88f4670e3f1c3e0300ad2

Fix suggestion to use expand_cxxstring_abis

---

src/AutoBuild.jl
test/building.jl

Fixes https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/636

Disallow `src_version` with build number already specified

---

Artifacts.toml
Manifest.toml
src/Rootfs.jl

This gets us a newer testsuite

Bump RootFS

---

Manifest.toml
src/Auditor.jl
src/AutoBuild.jl
src/auditor/extra_checks.jl
test/auditing.jl

Cleanup auditing a bit

---

docs/src/build_tips.md
src/Runner.jl

Add `bb_full_target` within the build environment.

---

.travis.yml
Artifacts.toml
Manifest.toml
Project.toml
src/AutoBuild.jl
src/Rootfs.jl

This is necessary for Julia 1.4+

Add compatibility hack for `arm-linux` -> `armv7l-linux` renaming.

---

src/AutoBuild.jl

Fixes errors such as these: https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=1351&view=logs&j=5b893806-aa4c-51ea-67ff-3e943c90e0eb&t=4c112957-7c31-5b1c-2ec3-067dfa49aab8

Add compat shim for Pkg on registration

---

deps/SnoopCompile/precompile/precompile_BinaryBuilder.jl
generate_precompile.jl
src/AutoBuild.jl
src/BinaryBuilder.jl

'sup dog, I heard you like compile times

Add SnoopCompile precompilation harness

---

src/wizard/deploy.jl

Should fix the error in https://github.com/JuliaPackaging/Yggdrasil/pull/491#discussion_r377583378, but I'd like to double check before merging this.

Check the string of the URL, not its representation

---

src/AutoBuild.jl

Nuke the old, generate compat entries for the new.

Fix JLL package generation on ARM

---

src/wizard/deploy.jl

Fix `ExecutableProduct` wizard generation trying to use `dir_path` kwarg

---

src/auditor/soname_matching.jl
test/auditing.jl

Fix link creation in `symlink_soname_lib`

---

docs/src/FAQ.md
docs/src/index.md
generate_precompile.jl
src/Prefix.jl
src/Sources.jl
src/wizard/deploy.jl
src/wizard/obtain_source.jl
test/basic.jl
test/building.jl
test/wizard.jl

Partially address #668 by adding the type `ArchiveSource`

Add ArchiveSource type

---

src/AutoBuild.jl

This paves the way for us to be able to download them in some other way.

Teach `rebuild_jll_package()` to restrain itself from downloading GH releases

---

src/DockerRunner.jl
src/Prefix.jl
src/Sources.jl
src/UserNSRunner.jl
src/wizard/deploy.jl
src/wizard/interactive_build.jl
src/wizard/state.jl
src/wizard/utils.jl
test/auditing.jl
test/building.jl

Implements https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/125.
Example PR: https://github.com/JuliaPackaging/Yggdrasil/pull/519

Diff source tree after interactive build

---

src/DockerRunner.jl
src/UserNSRunner.jl
src/wizard/interactive_build.jl
src/wizard/utils.jl
test/wizard.jl

Also a minimal fix to #677. This is on top of #678 because it touches some of the files and I'm hoping we can merge that soon-ish. If not I can do the rebase dance to switch the order of these though.

Wizard: Don't ignore error paths

---

src/Auditor.jl
src/AutoBuild.jl
src/auditor/compiler_abi.jl
test/auditing.jl
test/building.jl
test/runtests.jl

Add an audit warning if a package doesn't depend on CSL when it should

---

src/auditor/compiler_abi.jl

Fix warning about libgomp

---

Manifest.toml
Project.toml
src/AutoBuild.jl

See https://github.com/JuliaRegistries/RegistryTools.jl/issues/6#issuecomment-598345176

Allow registering versions older than existing ones

---

src/Auditor.jl
src/Prefix.jl
test/basic.jl

Fredrik says this is unnecessary, and he's probably right, but I
distinctly remember adding this for a reason.  Let's comment it out and
see if things still work.  :P

Comment out extraneous `resolve_versions!()`

---

src/Dependencies.jl
test/declarative.jl

fix JSON.lower(d::Dependency) for 1.4

---

src/Runner.jl

This should fix https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/729.  Note that a stubborn user can still call e.g. `patchelf --page-size 1024` and that will override the preference within the wrapper.

Generate `patchelf` wrappers for page alignment on `aarch64` and `ppc64le`

---

src/UserNSRunner.jl

Otherwise it's hard for users to diagnose what the issue is.

unpriv probing: Show errors when verbose

---

src/AutoBuild.jl
src/wizard/interactive_build.jl

Setup dependencies in the wizard matching the current compiler ABI

---

src/Prefix.jl

Trying to create a symlink on an existing directory would fail anyway, but at least this makes the error more clear.  This helped me to understand what's going on in https://github.com/JuliaPackaging/Yggdrasil/issues/844.

Fail gracefully when trying to symlink a directory that already exists

---

src/Runner.jl

Add `${prefix}/lib64/pkgconfig` to `PKG_CONFIG_PATH`

---

src/wizard/obtain_source.jl
src/wizard/yggdrasil.jl

Fix looking up paths in Yggdrasil

---

src/Wizard.jl
src/wizard/deploy.jl

Allow deploying a partial wizard state

---

docs/src/build_tips.md
src/Runner.jl

I always wondered why we don't have this variable :slightly_smiling_face:

Add `includedir` environment variable

---

src/Rootfs.jl

See https://github.com/JuliaPackaging/Yggdrasil/issues/948

Tell the user how to accept Xcode EULA when non-interactive

---

.github/workflows/TagBot.yml
.github/workflows/documentation.yml
.travis.yml
docs/src/build_tips.md

Also decrease frequency of TagBot to once per day

Move building of documentation to GitHub Actions

---

src/wizard/deploy.jl

Fix #784.  @aviks is this any better? :grimacing:

Clarify wizard prompt asking for file path

---

src/Wizard.jl
src/wizard/interactive_build.jl
test/wizard.jl

The wizard should suggest to press Enter instead of any key

---

src/AutoBuild.jl

We don't need to pass so many duplicates of Julia's libdir up through
the `LIBPATH_list` machinery in JLL packages; we can add it once at the
end for each package since we know this will always be the same for all
JLL packages.
This has the added bonus of fixing the Git_jll issues on MacOS, where
having Julia's libpcre in front of the installed LibPCRE2_jll was
causign problems.

Remove unnecessary duplicates in LIBPATH_list

---

src/AutoBuild.jl

This optional argument can be set to a string, which is then inserted at
the end of the generated __init__ methods. This allows inserting code
which initializes the JLL or in other ways makes it easier to use; e.g
for ncurses, it could set the TERMINFO env variable; for GMP, it could call
the `mp_set_memory_functions` function to ensure this copy of GMP uses
the same alloc/free functions as the GMP bundled with Julia.
This is motivated by issue #687 and would e.g. allow us to get rid of https://github.com/oscar-system/LoadFlint.jl (by changing https://github.com/JuliaBinaryWrappers/FLINT_jll.jl to contain the appropriate initialization calls).
Full disclaimer: the code in here is 100% untested! So it may even contain basic syntax errors. The reasons for this is that while I am willing to …

Add optional init_block kwarg to build_tarball

---

src/wizard/obtain_source.jl

Add missing import in wizard

---

docs/src/jll.md

Fix minor typo in jll.md

---

src/wizard/deploy.jl

checking for nothing in deploy

---

src/BinaryBuilder.jl

Import runshell from BinaryBuilderBase

---

src/Auditor.jl
src/auditor/dynamic_linkage.jl
src/auditor/soname_matching.jl

We weren't finding all of the libraries correctly, and even when we did, we didn't always complete all steps properly.
Fixes https://github.com/JuliaPackaging/Yggdrasil/issues/1438

Fix OpenLDAPClient_jll problems

---

src/wizard/deploy.jl
test/wizard.jl

Fixes https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/885

Write patches out to disk when deploying locally in Wizard

---

docs/src/build_tips.md
docs/src/building.md
docs/src/jll.md

Also, do not use Zlib in the override example, since you can't override Zlib as
it's baked into Julia.

[skip travis] Some improvements to documentation

---

src/AutoBuild.jl

Ref: https://github.com/JuliaPackaging/JLLWrappers.jl/issues/11

Fix writing of the init footer in the wrappers

---

src/wizard/obtain_source.jl

Wizard: add check for git repo when url starts with git://

---

src/AutoBuild.jl

Use backslash in paths of products for Windows

---

src/BinaryBuilder.jl

Autocomplete `runshell` and `run_wizard` in the REPL

---

src/wizard/github.jl
test/wizard.jl

Docs: https://docs.github.com/en/free-pro-team@latest/developers/apps/authorizing-oauth-apps
Screenshots:
```
Authenticating with GitHub
To continue, we need to authenticate you with GitHub. Please nagivate to
the following page in our browser and enter below code:
https://github.com/login/device
#############
#############
```

Implement new GitHub device authentication flow

---

src/auditor/dynamic_linkage.jl
test/auditing.jl

Fix valid_library_path to reject .sot extension

---

LICENSE.md

Since Julia Computing is a copyright holder for part of the BB work.

Add Julia Computing to list of contributors

---

contrib/generate_instructions_list.jl

Fix typo comment

---

src/auditor/extra_checks.jl
test/auditing.jl

[Auditor] Make sure libraries for eabihf match this ABI

---

src/AutoBuild.jl

Trying to load `MKL_jll` on Julia v1.6 I get
```
ERROR: LoadError: LoadError: InitError: Artifact "MKL" is a lazy artifact; package developers must call `using LazyArtifacts` in MKL_jll before using lazy artifacts.
```
This PR is meant to address this issue, but I'm not 100% sure this is correct.
I already created
[`LazyArtifacts.jl`](https://github.com/JuliaPackaging/LazyArtifacts.jl) for
compatibility with older Julia versions, but not yet registered it.

Use `LazyArtifacts` package when the artifact is lazy

---

src/Auditor.jl
src/auditor/filesystems.jl
test/auditing.jl

Related to https://github.com/JuliaLang/julia/issues/38993.  I verified locally
it works as I expect and will add tests later, after getting some feedback.

[Auditor] Add pass to make all binary files executable

---

Manifest.toml
src/AutoBuild.jl
src/BinaryBuilder.jl
src/wizard/interactive_build.jl
test/building.jl
test/jll.jl

Companion PR for BinaryBuilderBase: https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/43.  CC: @vchuravy 
NOTE: needs tests specifically for `HostBuildDependency`!

Setup and cleanup host dependencies during the build

---

Manifest.toml
azure-pipelines.yml

Ref: https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/112.

Update BinaryBuilderBase with LLVMBoostrap 11.0.1

---

test/wizard.jl

If we use only one specific port, when we run the tests in parallel only one
job manages to set up the server, and all the others will use the same.
However, the other jobs may need to serve different files, causing unrelated
failures in the tests.
This should fix #987.  I may need to polish this a bit, for example handle the
case where none of the ports is available.

Use different HTTP ports in the wizard tests

---

Manifest.toml
docs/src/index.md
docs/src/jll.md

* list videos talking about BinaryBuilder
* JLLs don't define `LIBPATH_env` anymore
Any other videos to suggest?  CC: @miguelraz

Some improvements to documentation

---

src/AutoBuild.jl

This will be required for the upcoming breaking release of RegistryCI.jl.

Add `* commit: mycommithash123` to the PR body when making PRs to the General registry

---

Project.toml
src/wizard/deploy.jl

Similar to #1008.  CC: @vchuravy

[Wizard] Fix name of function that had been renamed

---

docs/src/FAQ.md
docs/src/build_tips.md
docs/src/building.md

[Docs] Clarify target vs host dependencies

---

Project.toml
docs/src/build_tips.md
src/BinaryBuilder.jl

Fix https://github.com/JuliaPackaging/BinaryBuilderBase.jl/issues/151

Remove compat wrappers for old platforms

---

src/wizard/interactive_build.jl
test/wizard.jl

BBBase changed the layout of the $prefix/artifacts directory, such that
the fix in #931 was no longer effective. Instead of closely coupling
BB to BBBase just move the rm part to BBBase[1] and do a proper
cleanup/setup cycle here.
[1] https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/183

In `bb add`, unlink artifacts, but move rm to BBBase

---

docs/src/jll.md

Instead of https://github.com/JuliaLang/Pkg.jl/pull/2889

[docs] explain use of Preferences.jl to override JLL

---

src/AutoBuild.jl
test/jll.jl

Allow for non jll dependencies

---

docs/src/FAQ.md

update dead link in documentation

---

src/auditor/instruction_set.jl

Was just browsing and saw this. I guess this can be `const`.

make a global variable const

---

src/auditor/instruction_set.jl

remove a spurious `@time`

---

.github/workflows/documentation.yml
Manifest.toml
Project.toml
azure-pipelines.yml
src/AutoBuild.jl

Follow up to https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/129

Require Julia v1.7

---

src/AutoBuild.jl

[Autobuild] Propagate `julia_compat` for --deploy mode

---

src/AutoBuild.jl

CC: @vchuravy.  Verified it works in https://github.com/giordano/finufft_jll.jl/commit/e63f2118485986a074719c26436706ff170196e4
Fix #1179.

[AutoBuild] Make artifacts lazy by default if augmenting platform

---

Manifest.toml
Project.toml
docs/src/building.md
src/AutoBuild.jl
src/BinaryBuilder.jl

Follow-up to https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/249.  CC: @vchuravy

[AutoBuild] Filter out non-build deps before calling `setup_dependencies`

---

Manifest.toml

[CI] Update Manifest.toml

---

docs/src/build_tips.md

I have absolutely no idea why I removed this section in #1068, I feel like it may have been an accidental mistake, because I've always assumed this section was there, I had no intention of removing this crucial bit of information.

[docs] Restore section about build strategy

---

src/AutoBuild.jl
test/basic.jl
test/jll.jl

[AutoBuild] Add compat bounds for stdlibs in generated JLLs

---

Manifest.toml
Project.toml
src/AutoBuild.jl
test/auditing.jl
test/building.jl

Companion PR to https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/357

[AutoBuild] Forward `clang_use_lld` keyword argument to `preferred_runner`

---

.github/workflows/documentation.yml
docs/src/build_tips.md
src/wizard/hints.jl

[docs] Add more build tips about CMake and linking to BLAS

---

Project.toml

Release v0.5.8

---

src/AutoBuild.jl

```julia-repl
julia> Tuple{<:UInt} == Tuple{UInt}
true
```

slightly simplify type definition: `Tuple{<:T}` -> `Tuple{T}`

---

src/AutoBuild.jl

[AutoBuild] Fix value of `jllwrappers_compat`

---

src/AutoBuild.jl
test/building.jl

Support platform augmentation for riscv64

---

Project.toml
src/AutoBuild.jl
test/building.jl

Needs https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/431.  CC @wsmoses.

[AutoBuild] Support compression formats different from GZip
