src/Runner.jl
src/UserNSRunner.jl

This bumps up to a new rootfs that incorporates https://github.com/staticfloat/julia-docker/commit/7304d4b9772d40a1094b14401e2db0ad54897db2.  This defaults `CC` and `CXX` to `clang` and `clang++`, respectively, but it still has `gcc` and friends available if someone really wants to use those.  I have confirmed that compiling a "Hello World" with `clang++` creates code that successfully links against `libc++` and can run on an actual mac machine.

Add `clang` and `clang++` as the default `CC` and `CXX` when targeting macOS

---

deps/sandbox.c

Not sure why that was there, I'm sure I had a reason at some point. Oh well, this was causing travis timeouts rather than failures.

Remove sleep on assertion fail

---

src/Auditor.jl
src/wizard/interactive_build.jl

Fixes looking for the script in the wrong location and a
use of the removed `overlay` option.

Misc bug fix

---

src/QemuRunner.jl

The `mapping` keyword was initialized to nothing; it seems like it wasn't be returned by accident.

Fix "no method matching start(::Void)" with QemuRunner

---

src/wizard/obtain_source.jl

This fixes the error I was getting previously:
```
ERROR: LoadError: LoadError: LoadError: LoadError: UndefVarError: @gc_preserve not defined
Stacktrace:
[1] top-level scope
[2] include at ./boot.jl:279 [inlined]
[3] include_relative(::Module, ::String) at ./loading.jl:509
[4] include at ./sysimg.jl:15 [inlined]
[5] include(::String) at /Users/ericdavies/.julia/v0.7/BinaryBuilder/src/BinaryBuilder.jl:4
[6] top-level scope
[7] include at ./boot.jl:279 [inlined]
[8] include_relative(::Module, ::String) at ./loading.jl:509
[9] include at ./sysimg.jl:15 [inlined]
[10] include(::String) at /Users/ericdavies/.julia/v0.7/BinaryBuilder/src/BinaryBuilder.jl:4
[11] top-level scope
[12] include at ./boot.jl:279 [inlined]
[13] include_relative(::Module, ::String) at ./loading.jl:509
[14] …
```

Fix @compat_gc_preserve on 0.7

---

src/BinaryBuilder.jl

https://github.com/JuliaLang/julia/pull/25459 moved `Libdl` to the
stdlib, which means that we need to explicitly import it now before we
can do things like `Libdl.dlopen()`.

Explicitly import `Libdl`

---

REQUIRE
src/wizard/deploy.jl

Usage:
```
julia> BinaryBuilder.setup_travis("Keno/Rmath-julia")
GitHub user name: Keno
Creating a github access token.
We will use this token to create to repository, and then pass it to travis
for future uploads of binary artifacts.
You will be prompted for your GitHub credentials.
Please enter the github.com password for Keno:
Two factor authentication in use.  Enter auth code.
> 318501
Asking travis to sync github and waiting until it knows about our new repo.
This may take a few seconds (or minutes, depending on Travis' mood)
Done waiting
deploy:
provider: releases
api_key:
secure: HgZMI82Uup5x5cfmhK26mp6KbpHkRvGjnrGKghoGVfuY5ewwfM9UZ6ln0XxltjDP5cvCh4r3EpJNbYe9SjzF2ECnIn3xdJarNfXZME/CzXe4Lf0CA2WzXaUZT+NJKlH873y2n5rP5nPsUE0KP+5YoE3ZM5t80yc5uWlKaMdZl4R8YKkA2Lwzsy6YdvAVTB9vKEY9ETn6AySXc6 …
```

Split out travis deploy as a separately-callable function

---

src/wizard/interactive_build.jl

Stacktrace: https://www.dropbox.com/s/4hsozxml0gmvti5/Screenshot%202018-01-30%2016.54.38.png

Use rm instead of rmdir (because it exists)

---

.travis.yml

Now that the sandbox is part of the rootfs, our CI currently
does not test changes to the sandbox anymore. Add a build
step that uses the sandbox from this repo.

Add a travis build step that tests sandbox changes

---

src/AutoBuild.jl

Allow binaries installed within the prefix to be used regardless of our currently running platform.

Invert installation checks

---

src/wizard/utils.jl

This fixes the `joinpath(::Void, ::String)` method error you can get right now when using a relatively recent/fancy remote `build.jl` file.

Provide a fake `@__DIR__` so that remote `build.jl` files don't freak out

---

docs/src/index.md
src/Auditor.jl
src/AutoBuild.jl
src/BinaryBuilder.jl
src/QemuRunner.jl
src/UserNSRunner.jl
src/compat.jl
src/wizard/deploy.jl
test/build_libfoo_tarballs.jl
test/runtests.jl

This greatly simplifies the `build_tarball.jl` files we've been
generating, bundling together the functionality that we have, so far,
been embedding in repositories scattered far and wide.  This also firms
up the rules of when a `build.jl` file is generated a little bit more.

Create new top-level abstraction `build_tarballs()`

---

src/RootFS.jl
src/UserNSRunner.jl

Don't use `sudo` if we're already `root`.  Also allows for using `su` if `sudo` doesn't exist.

Better asking for privileges

---

docs/src/environment_variables.md
src/BinaryBuilder.jl
src/RootFS.jl
src/UserNSRunner.jl
test/runtests.jl

This will error out if the user attempts to run the sandbox with any kind of bindmounting that would involve `ecryptfs` directories, which is the case on e.g. Ubuntu machines with encrypted home directories.  This is undesirable because it triggers kernel bugs.

Deal with `ecryptfs` directories

---

src/AutoBuild.jl
src/Runner.jl
src/wizard/utils.jl

Before merging this, add a test case to ensure that this doesn't break in the future.  The specific break was that when installing a dependent tarball, the `build.jl` would fail because the `deps.jl` file generation would fail, claiming that the requested products were unsatisfied, likely due to the fact that they were on the wrong stinkin' platform.

Override `write_deps_file()` when installing dependencies

---

src/QemuRunner.jl

ref #153. Maybe not the desired long-term fix, but this makes the macOS experience much less annoying.

Use stty to change interrtupt when running interactive QEMU shell

---

src/RootFS.jl
src/UserNSRunner.jl

This fixes the mysteriously missing `LD_LIBRARY_PATH` problems when running on e.g. Arch

Force-set `LD_LIBRARY_PATH` when using `sudo` on privileged builders

---

src/auditor/dynamic_linkage.jl

I guess the principle here is to ignore libraries that always ship with the OS?  If so, libdl and librt should qualify.

more libs to ignore

---

src/Auditor.jl
src/auditor/symlink_translator.jl

`Bzip2Builder` doesn't make good symlinks, they're all absolute.  No harm no foul, let's just automatically translate them.

Translate absolute symlinks to relative in an audit pass

---

src/AutoBuild.jl
src/Dependency.jl
src/auditor/dynamic_linkage.jl
src/wizard/utils.jl

* Fix two simultaneous builders occasionally stepping on eachother's toes
* Warn if, after a build, we still don't satisfy a particular product.  We're not making this fatal, but it will be if it is still the case after installation on a user's machine.
* Make the dependency uninstallation machinery more robust.

Various fixes

---

src/AutoBuild.jl

As explained in JuliaPackaging/BinaryProvider.jl#59. 
Don't merge until a new version of BinaryProvider is tagged (to have the `isinstalled` function from JuliaPackaging/BinaryProvider.jl#60).
cc @staticfloat

change build.jl to re-download when tarball hash changes

---

.travis.yml
src/Auditor.jl
src/AutoBuild.jl
src/RootFS.jl
src/Runner.jl
src/UserNSRunner.jl
src/auditor/dynamic_linkage.jl
src/auditor/instruction_set.jl
test/runtests.jl

Lots of goodies in this one, including much better macOS C++ toolchain setup, FreeBSD and musl linux shards, as well as the products of a completely new shard buildsystem.
Many thanks to @wdv4758h and @ararslan for their help getting the FreeBSD toolchain setup!

Fixed OSX toolchain, add FreeBSD/musl platforms

---

src/RootFS.jl
src/Runner.jl

We were using `$target` to communicate to `clang` as a default target (beyond just what it's compiled with) but that was being overridden by `configure` scripts.  This uncrosses those two wires.

Fix `./configure` for clang-based builds

---

src/Auditor.jl
test/runtests.jl

But only if all `.dll` files are held within `lib` by a simple build system.  Anything complicated is going to require a change in the build system or manual intervention.

Automatically move `.dll` files from `lib` to `bin`

---

src/auditor/instruction_set.jl

I think this fixes https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/241. However, the `IOBuffer` might still be quite large. I've confirmed that it fixes https://github.com/ViralBShah/ArpackBuilder/issues/1
cc: @viralbshah

Avoid reading all lines at once by using eachline instead of readlines

---

.travis.yml
src/Auditor.jl
src/AutoBuild.jl
src/Dependency.jl
src/auditor/dynamic_linkage.jl
test/package_tests/.gitignore
test/package_tests/runtests.jl
test/runtests.jl

@andreasnoack I think this change is necessary to get `ArpackBuilder` working; it changes a bit how we do our linking, so this isn't going to get merged very quickly because I still need to go through some of our larger customers and make sure that they are still able to build after this change, but I can at least `Libdl.dlopen("libarpack.so")` successfully if I build it with this branch.

Change relinking to use `$ORIGIN` and `@rpath` properly

---

deps/sandbox.c
src/QemuRunner.jl

QEMU commit
qemu/qemu@a8aa6197a2aec4ca4ef5a4fdd8a39216e7f42da6 [chardev/char-socket: add POLLHUP handler]
caused QEMU to start dropping any remaining data if the socket
is closed before all the data has been processed. To avoid this,
write back an acknowledgement when we're doing processing the data,
so we know that it's safe to close the socket.

 Add acknowledgement after init is done parsing its arguments

---

src/Dependency.jl
test/runtests.jl

This is a significant increase in strictness, however now that we have `--debug` it's doable.
With this change, any command that comes back nonzero (e.g. a failed patch, or an `rm foo` when `foo` does not exist) will cause the build to end.  Running with `--debug` will, of course, still drop into a buildshell, but this should significantly reduce confusion when, for example, patches stop applying cleanly because of an upgraded version.

Cause all errors to stop the build

---

src/Runner.jl
test/runtests.jl

To be used as: `mv libfoo.so libfoo.${dlext}`, for buildsystems that hardcode `.so` onto the ends of shared libraries, for example.

Add `dlext` environment variable to build environment

---

src/AutoBuild.jl
src/RootFS.jl

When running from within Docker, we seem to be very limited in terms of how many loopback devices we can use.

Auto-unmount shards, so as to not exhaust number of loopback devices

---

src/RootFS.jl

This is possible now that the images are all <2GB, as we have shattered the build image across multiple shards.

Use fastly to cache rootfs images

---

src/Dependency.jl

Closes https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/280

Add `dep.platform` into the error message when a build fails

---

src/AutoBuild.jl
src/auditor/dynamic_linkage.jl
src/wizard/deploy.jl
src/wizard/state.jl
test/package_tests/runtests.jl
test/runtests.jl
test/wizard.jl

This embeds versions into output tarball and build.jl files.  This is a breaking change, as `build_tarballs.jl` files now must pass in a `version` to `build_tarballs()`.

Version output products

---

src/AutoBuild.jl
src/wizard/utils.jl

the real function accepts kwargs, but these stubs did not, so if the
user's dependent build.jl used a keyword argument it would crash out
while setting up the workspace

write_deps_file stubs now accept keyword args

---

REQUIRE
src/AutoBuild.jl
src/RootFS.jl
src/wizard/deploy.jl

Write our own version to do what we want.  Also fix logic problems.  This should fix https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/340

`LibGit2.get(cfg, key, default)` doesn't mix types

---

src/RootfsHashTable.jl
src/auditor/dynamic_linkage.jl

The path to `clang` and `clang++` embedded within the cmake toolchain files was borked, fix that.

Fix clang path in cmake toolchains, rework dynamic library mappings for the umpteenth time

---

src/Rootfs.jl
src/RootfsHashTable.jl

@barche here's the fix for your C++ woes on OSX.

Update RootFS to fix clang `libc++` linkage on OSX

---

src/RootfsHashTable.jl

Includes https://github.com/JuliaPackaging/Yggdrasil/commit/7a671df925eb839d9afe8b5c051d698cb2e9e79a to fix GDALBuilder

New BaseCompilerShard tarballs

---

src/wizard/deploy.jl

Here's my attempt at fixing #396. I was able to BinaryBuilder to configure GitHub and Travis correctly. However, while it *does* complete successfully, the following error is logged:
```
Enter your desired license [MIT]:
┌ Warning: a SecretBuffer was `shred!`ed by the GC; use `shred!` manually after use to minimize exposure.
└ @ Base secretbuffer.jl:169
┌ Error: Exception while generating log record in module Base at secretbuffer.jl:169
│   exception =
│    task switch not allowed from inside gc finalizer
│    Stacktrace:
│     [1] try_yieldto(::typeof(Base.ensure_rescheduled), ::Base.RefValue{Task}) at ./event.jl:187
│     [2] wait() at ./event.jl:255
│     [3] uv_write(::Base.TTY, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:782
│     [4] unsafe_write(::Base.TTY, ::Ptr{UInt8}, ::UInt64) at …
```

[WIP] Initial fix for #396

---

src/Rootfs.jl
test/basic.jl

Provides exclusion within supported_platforms() to move to an opt-out style BinaryBuilder approach. 
```julia
>supported_platforms(exclude=[Windows(:i686),Windows(:x86_64)])
11-element Array{Platform,1}:
Linux(:i686, libc=:glibc)                    
Linux(:x86_64, libc=:glibc)                  
Linux(:aarch64, libc=:glibc)                 
Linux(:armv7l, libc=:glibc, call_abi=:eabihf)
Linux(:powerpc64le, libc=:glibc)             
Linux(:i686, libc=:musl)                     
Linux(:x86_64, libc=:musl)                   
Linux(:aarch64, libc=:musl)                  
Linux(:armv7l, libc=:musl, call_abi=:eabihf) 
MacOS(:x86_64)                               
FreeBSD(:x86_64)  
```
A couple of reasons why this might be nice:
1. The current approach tends to result in manual lists of …

Optional excluding of Products from supported_platforms()

---

src/Runner.jl

Also fix the test for `SUPER_VERBOSE`.

Quote variables in compiler wrappers

---

src/Auditor.jl
src/AutoBuild.jl
src/wizard/interactive_build.jl
src/wizard/utils.jl

<s>This only checks in the `audit` that we're shipping the license file, but doesn't automatically install it if present in the source distribution.  I still have to find a good place where to hook in order to automatically install the license file :thinking: </s>
Ref #309.

Check that we are shipping a license file and auto install licenses

---

test/build_tests/libfoo/meson.build

building for macOS:
```
cmd LC_RPATH
cmdsize 40
path @executable_path/../lib (offset 12)
```
building for Linux:
```
RPATH                $ORIGIN/../lib
```

In meson test, install binary and library and set rpath

---

src/Rootfs.jl

This bug prevented `macos_sdk_already_installed()` to run.

Fix variable name in macos_sdk_already_installed()

---

src/wizard/github.jl
src/wizard/utils.jl

As [suggested by Keno](https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/465#issuecomment-549181497), I've looked into `Base.getpass`.  However, this _always_ appends "`: `" to the prompt, which doesn't play nicely with the custom prompt used by `BinaryBuilder.nonempty_line_prompt`.  Probably on Windows one could use `devnull` as output stream, but this wouldn't work on the other systems.  Thus, I've defined a function based on `Base.getpass` which never writes a prompt, as this is the current need in BB.  Maybe something like this should go into `Base.getpass`?
Fixes #465.

Do not echo input when asking for a password in the wizard

---

src/wizard/github.jl
test/wizard.jl

Fix `github_auth(allow_anonymous=true)` when `GITHUB_TOKEN` is not set

---

docker_images/v1.3/Dockerfile

This should fix our docker images not being updated.

Force invalidation of docker cache for new versions of BB

---

src/AutoBuild.jl

Hopefully this will fix problems where we try to register the same version twice.

Force-update the registry every time we look for a new build number

---

src/wizard/deploy.jl
src/wizard/utils.jl
src/wizard/yggdrasil.jl

For the truly, incurably, lazy among us, here is some preposterously
convenient tooling; As you browse the latest Yggdrasil PRs from the
comfort of your la-z-boy coding throne, whenever you feel like digging
deeper into the mysteries of why that blasted binary won't build, you
can now simply run `test_yggdrasil_pr(XXX)` to get yourself a build (and
the subsequent debug shell when it breaks).  The BinaryBuilder
revolution marches onwards.

Add `test_yggdrasil_pr()`

---

src/AutoBuild.jl
src/wizard/yggdrasil.jl
test/building.jl

Also update registry more automatically, but only once per session

Give better error messages when JLL packages do not exist.

---

docker_images/v1.3/Dockerfile
src/AutoBuild.jl

Submit PRs from the proper fork, use the proper email for `@jlbuild` commits, etc...

Fixes to get JLL autoregistration working properly

---

src/AutoBuild.jl
src/wizard/utils.jl

This allows us to clean up the build prefix afterward

Work around `go`'s penchant to mark directories as read-only

---

Manifest.toml
Project.toml
docker_images/v1.3/Dockerfile
docs/Manifest.toml
src/AutoBuild.jl
src/BinaryBuilder.jl

Preposterously easy.  Once I could build `ghr` of course, heh.

Use `ghr_jll` to provide `ghr` on all platforms

---

Manifest.toml
Project.toml
src/Auditor.jl
src/AutoBuild.jl
src/auditor/compiler_abi.jl
src/auditor/filesystems.jl
src/auditor/instruction_set.jl
src/auditor/soname_matching.jl
src/auditor/symlink_translator.jl
src/compat.jl
src/wizard/interactive_build.jl
src/wizard/obtain_source.jl
src/wizard/state.jl
src/wizard/utils.jl
src/wizard/yggdrasil.jl
test/auditing.jl
test/basic.jl
test/building.jl
test/wizard.jl

On current master, binary dependencies were not added to the build environment when running the wizard, this should be fixed by this PR. I am not very familiar with the codebase, so maybe there are better ways to do this.

Add dependencies when running the wizard

---

src/AutoBuild.jl
src/Products.jl

We don't have dependencies, so this will fail in general

Don't `dlopen()` during JLL rebuilding

---

src/AutoBuild.jl
src/BinaryBuilder.jl

This is useful in order to keep the versions in the log file.
Maybe too many commands?  Do you suggest some other commands to log?

Print compiler versions before compiling

---

Project.toml

Registrator v1.0.1 removed RegEdit, which breaks automatic JLL registration until BinaryBuilder is ported to use RegistryTools.

Fix Registrator compatibility to v1.0.0

---

src/Auditor.jl
test/basic.jl

`collect_files` currently only looks for files, so the auditor doesn't replace symlinks to directories with a copy of the directory, and leaves the symlink there instead.
Observed in https://github.com/JuliaPackaging/Yggdrasil/pull/229#issuecomment-557949832.  Also [` WCS-v6.4.0+0 `](https://github.com/JuliaBinaryWrappers/WCS_jll.jl/releases/tag/WCS-v6.4.0%2B0) has a symlink to a directory in the tarballs for Windows.

Optionally collect directories in `collect_files`

---

src/AutoBuild.jl

instead of the _jll module src directory
Since I'm not sure the following behavior is intended (see also slack thread):
```julia
julia> using GEOS_jll; GEOS_jll.prefix
"C:\\Users\\visser_mn\\.julia\\packages\\GEOS_jll\\8ezLq\\src\\"
```

set the prefix to the prefix

---

src/AutoBuild.jl

Should fix
```
julia> using LuaCall
[ Info: Precompiling LuaCall [b19d909c-f536-5a7e-8424-a4fb7ce1e4d7]
WARNING: redefining constant LIBPATH_list
WARNING: redefining constant LIBPATH_list
```

Don't overwrite PATH_list and LIBPATH_list

---

src/AutoBuild.jl

This allows users that really want to jump through hoops to avoid bifurcating their packages across the 1.3 divide to do so.

Set JLL packages to be installable but not loadable on 1.0-1.2

---

src/wizard/github.jl
test/wizard.jl

Ref #476.  See https://github.com/JuliaLang/julia/issues/33628#issuecomment-550030136

Throw error when authenticating if input is closed and GITHUB_TOKEN is empty

---

src/BinaryBuilder.jl
src/Prefix.jl

This fixes some tests on MacOS, and should probably fix #541 as well.

Fix tests on MacOS

---

src/AutoBuild.jl

Honestly I'm a bit confused about how Julia-provided libraries are scattered around, to be sure I'm adding all possible directories.  Ref https://github.com/JuliaGraphics/Gtk.jl/issues/461.

Add Sys.BINDIR to LIBPATH_list in JLL wrappers for Windows

---

src/AutoBuild.jl

This allows you to deploy the JLL wrapper package along with the binaries so they can be tested, without needing to register the package in General.
(This PR is built on top of #536, so that should be merged first)

build and push the JLL package on `--deploy`

---

src/UserNSRunner.jl

I think this might actually fix the `EROFS` we keep seeing on CI :D

Properly unmount `other_shard` within `probe_unprivileged_containers()`

---

.codecov.yml

Not that the line
```yaml
comment: false
```
is working particularly well, even though [it does seem correct](https://docs.codecov.io/docs/pull-request-comments#section-disable-comment)...

Add small threshold for codecov success

---

Artifacts.toml
src/AutoBuild.jl
src/DockerRunner.jl
src/Rootfs.jl
src/UserNSRunner.jl

We will now ship multiple LLVM versions as well as GCC versions,
providing for the same `preferred_llvm_version` style kwargs.  This will
allow us to work around LLVM bugs and such.

Allow selection of LLVM version

---

Artifacts.toml
src/Rootfs.jl

This should fix Valentin's LLVM build woes

Bump `PlatformSupport` shards to fix CMake toolchain path issues

---

docs/src/build_tips.md
docs/src/environment_variables.md
src/Runner.jl

```
julia> BinaryBuilder.runshell(Linux(:x86_64));
sandbox:${WORKSPACE} # echo ${nproc} 
8
sandbox:${WORKSPACE} # logout
julia> ENV["BINARYBUILDER_NPROCS"] = "5"
"5"
julia> BinaryBuilder.runshell(Linux(:x86_64));
sandbox:${WORKSPACE} # echo ${nproc} 
5
```
however there is no validation of the input

Define `BINARYBUILDER_NPROC` to override `${nproc}`

---

docker_images/v1.3/Dockerfile

When adding master `BinaryBuilderversioninfo()` doesn’t provide useful insights
about the exact version used.

Dev BinaryBuilder in Dockerfile, instead of adding master

---

Artifacts.toml
src/AutoBuild.jl

This, the result of https://github.com/JuliaPackaging/Yggdrasil/commit/4dd0cddb9b3e416ccf19f8bebae353b89d9b0b17, should fix https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/563

Bump LLVM shards to fix libxml2 issues

---

Artifacts.toml
src/Rootfs.jl
src/Runner.jl

* Rebuilt `PlatformSupport` shards to include manual installation of `libc++` headers
* Disabled default search path in `clang`, manually overrode to ignore host headers
* Fixed some compiler warnings when using `-fsyntax-only`

Fix macOS libc++ include problems

---

src/wizard/utils.jl
test/basic.jl

`build_tarballs`: accept dependencies with UUID's specified in the `PackageSpec`. Makes e.g.
```
dependencies = [
PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95")
]
```
work.

build_tarballs: accept dependencies with UUID's specified

---

src/wizard/deploy.jl

Print `supported_platforms()` when wizard recipe builds for all platforms

---

Artifacts.toml
src/Rootfs.jl

Thanks to Valentin, we have the latest in LLVM-based BB shard options

Add `LLVM@9` shard

---

Artifacts.toml
src/Runner.jl

Fix multiple problems with LLVM:
* Fix `LLVM` invoking the wrong linker on every system except MacOS/FreeBSD/host (we now generate `ld.${target}` compiler wrappers and use `-fuse-ld=${target}` unconditionally)
* Include clang patch for musl triplets so it can find `libstdc++`.
* We use `libstdc++` with `clang` on all platforms except for FreeBSD and MacOS, to match Julia.

Fix LLVM testsuite

---

src/AutoBuild.jl

I've always found this error message not very helpful as it doesn't tell you what's the faulty source.

Improve error message about wrong source specification

---

src/auditor/instruction_set.jl

This should fix the issue reported in https://github.com/JuliaPackaging/Yggdrasil/pull/344#issuecomment-569554838

Ignore empty columns in `objdump` output

---

.travis.yml

Tests with `BINARYBUILDER_RUNNER=docker` are failing because of #593.  This pull request uses Julia 1.3.0 in this case, which at least works around the issue.  When #593 is fixed, this change can be reverted.

Run tests with docker on Julia 1.3.0

---

Artifacts.toml
src/AutoBuild.jl
src/Rootfs.jl

Since we don't use QEMU anymore, disk I/O isn't quite as high-priority
as it once was; it's okay to rely on `docker` for reasonable disk I/O.

Remove `tmpify_srcdir` step and upgrade RootFS

---

src/Runner.jl

In https://github.com/JuliaPackaging/Yggdrasil/pull/380 I spent a lot of time before figuring out that ccache was doing a mess and not generating the Fortran module files.
Basic support for Fortran was added in ccache v3.3, but then removed in v3.7 because it wasn't working very well (from [release notes](https://github.com/ccache/ccache/blob/87a4c8e65be9e70aa395246ada688a51bfd0749f/doc/NEWS.adoc#changes-1)), as I can confirm!  We're using ccache 3.5, which is well in between.

Disable ccache for gfortran, as it isn't well supported anyway

---

src/AutoBuild.jl
src/DockerRunner.jl
src/Runner.jl
src/UserNSRunner.jl

For context, it was reported in
https://github.com/JuliaCI/BaseBenchmarks.jl/issues/253 that dlopening a library
compiled with `-Ofast` caused the denormal mode to be changed.
This PR disallows using compiler flags that are known to cause troubles.

Stop compilers from using known unsafe options

---

src/AutoBuild.jl
src/compat.jl

This allows generating an `Artifacts.toml` marking the tarballs for lazy download.  See for example [this `Artifact.toml`](https://github.com/giordano/HelloWorldC/blob/master/Artifacts.toml).
I think one possible use case is to make lazy JLL packagess with large tarballs and to be used optionally in Julia packages, like MKL_jll.
Still to do:

Add keyword argument `lazy_artifacts` for `build_tarballs()`

---

src/wizard/deploy.jl

I think this removes the last extra whitespaces in the script generated by the wizard.  With no dependencies the result should simply be:
```
dependencies = [
]
```

Avoid blank line when there are no dependencies

---

src/Rootfs.jl
src/wizard/deploy.jl
src/wizard/interactive_build.jl
src/wizard/obtain_source.jl
src/wizard/state.jl
test/wizard.jl

I'm not very familiar with wizard code.  The wizard now it's failing for me during audit of the second platform tested, quite possible I did something wrong in `src/wizard/interactive_build.jl`.
Maybe this could be the base for an advanced option to activate on request, that lets the user choose other compiler-related stuff, like the preferred GCC and LLVM.

Allow selection of compilers in the wizard

---

src/Auditor.jl
src/auditor/extra_checks.jl

This is not a real issue for the dynamic loader, which seems to be happy to open a library with the OS/ABI bit not set to FreeBSD, but we found already a few times that a FreeBSD library with this bit set to 0x00 (System V) upsets our linker, which thinks that this is a foreign library.
I created a new file `auditor/extra_checks.jl` because I think there might be other platform-specific or not very well classified checks in the future.

Add audit pass to check OS/ABI for FreeBSD libraries

---

src/Runner.jl
src/UserNSRunner.jl
src/auditor/compiler_abi.jl
test/auditing.jl
test/build_tests/cxxstringabi_tests/Makefile
test/build_tests/cxxstringabi_tests/lib.cc

We were accidentally stripping out ABI information from our platform
objects while generating compiler wrappers, resulting in `cxxstring_abi`
settings being ignored.  In order to ensure that this does not happen
again, we've added some more tests ensuring that when we ask to build a
`cxx11` library, we actually get what we asked for.
Also, the `cppfilt()` function wasn't working at all because I forgot to `seek(input, 0)` before sending it into the `run_interactive()`.

Fix dead `cxxstring_abi` code paths

---

src/AutoBuild.jl
src/DockerRunner.jl
src/Rootfs.jl
src/Runner.jl
src/UserNSRunner.jl
src/wizard/deploy.jl
src/wizard/obtain_source.jl
test/basic.jl
test/wizard.jl

This should solve the issue we had in https://github.com/JuliaPackaging/Yggdrasil/pull/369 where the build environment had libgfortran3, but a dependency (namely OpenBLAS) was downloaded in its libgfortran5 flavour.
I tested this PR locally with https://github.com/JuliaPackaging/Yggdrasil/pull/378.

Setup dependencies that match the GCC ABI of the compiler

---

src/Rootfs.jl
test/basic.jl

I missed to do these changes in #604.
I feel like `CompilerShard` should have a `build::CompilerBuild` field instead of `version::VersionNumber`, this would simplify even further the two functions in this PR, however I don't see how "RootFS" and "PlatformSupport" would fit into a `CompilerBuild` :thinking:

Simplify `preferred_libgfortran_version` and `preferred_cxxstring_abi`

---

src/wizard/obtain_source.jl
test/wizard.jl

This is done to match the fact that the default LLVM compiler is the latest one,
rather than the oldest one as it is for GCC.

Reverse the order of LLVM compilers proposed in the wizard

---

Artifacts.toml
src/Rootfs.jl
src/Runner.jl
test/auditing.jl
test/building.jl

This should get coverage of the strange case where someone manages to ignore our compiler choice and generate cxx11 code on a cxx03 build.
Don't merge until we are certain that the coverage includes all branches of the cxxstring abi checking functions

Add cxxstringabi mismatches to tests and $CC -lgfortran tests

---

.travis.yml

This also fixes warnings in the configuration of the build

Run Travis only on specific branches

---

src/AutoBuild.jl
test/basic.jl

The call to `jll_uuid` to get the UUID of the dependencies was erroneously
removed in #643, this commit reverts that change and adds regression tests to
avoid similar errors in the future.

Fix building of project dict for registration

---

src/AutoBuild.jl

The wrong ordering might confuse users.

Fix ccall arguments in example usage

---

src/AutoBuild.jl

`build_project_dict()` expects Dependencies, so the prior transformation of dependencies into PkgSpecs breaks local deploy/registration.
Without this following error occurs:
```
Info: SHA256 of hidapi.v0.9.0.i686-w64-mingw32.tar.gz: ea10d874bbc9aa07f56f8f88a0559f2b7c9f13d5eb16a10362500685aa0feff8
[ Info: Committing and pushing hidapi_jll.jl wrapper code version 0.9.0+0...
[ Info: Generating jll package for i686-w64-mingw32 in /home/gerhard/.julia/dev/hidapi_jll
ERROR: LoadError: MethodError: no method matching build_project_dict(::String, ::VersionNumber, ::Array{Pkg.Types.PackageSpec,1})
Closest candidates are:
build_project_dict(::Any, ::Any, ::Array{Dependency,N} where N) at /home/gerhard/.julia/packages/BinaryBuilder/xbKKQ/src/AutoBuild.jl:1263
Stacktrace:
[1] …
```

Fix error in local registration/deployment

---

src/AutoBuild.jl

Not sure why this doesn't work

`remoteurl` seems to disable fetching, for some reason.

---

src/AutoBuild.jl

This feature is useful in theory, but causes a lot of harm in practice, for example if `get_next_wrapper_version` fails to get the version number right for unknown reasons.
Fix #554.

Do not replace existing artifacts

---

src/BinaryBuilder.jl

This is one step removed from something we can find in GitHub, but at least it'll help more than `v0.2.3`. :P

If we can't get the `gitsha`, then return the tree hash

---

.travis.yml

On travis, we default to squashfs shards, so in order to test unpacked shards,
we need to set the env var to false. Also it was misspelled for the one instance
where it was set.

Update travis configuration to match comments

---

src/AutoBuild.jl

This is what Julia v1.3 is doing now on armv7l to select the best platform in the JLL wrapper, for example for OpenSpecFun:
```julia
julia> using Pkg, Pkg.BinaryPlatforms, Pkg.Artifacts, Libdl
julia> import Base: UUID
julia> artifacts_toml = joinpath(@__DIR__, "..", "Artifacts.toml")
"/home/mose/.julia/packages/OpenSpecFun_jll/G7uZt/src/../Artifacts.toml"
julia> artifacts = Pkg.Artifacts.load_artifacts_toml(artifacts_toml; pkg_uuid=UUID("efe28fd5-8261-553b-a9e1-b2916fc3738e"))
Dict{String,Any} with 1 entry:
"OpenSpecFun" => Dict{String,Any}[Dict("libgfortran_version"=>"5.0.0","arch"=>"x86_64","git-tree-sha1"=>"a81bd38b8d5212f36c6b7fbe09562daef575…
julia> platforms = [Pkg.Artifacts.unpack_platform(e, "OpenSpecFun", artifacts_toml) for e in artifacts["OpenSpecFun"]]
39-element …
```

Fix filtering of armv7l platforms in JLL wrappers for Julia v1.3

---

src/Runner.jl

This avoids things breaking because of the flags we insert.  Example: https://github.com/JuliaPackaging/Yggdrasil/pull/559

Add `-Wno-unused-command-line-argument` to `clang` wrapper

---

src/AutoBuild.jl
src/Declarative.jl
src/Products.jl
test/build_tests/libfoo/CMakeLists.txt
test/building.jl
test/declarative.jl

As discussed in https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/393#issuecomment-581182957, this adds basic support for macOS frameworks, limited to the following:
* Find a framework that matches the provided name with the `.framework` suffix
* Resolve the library that is inside the framework with its version
On non-macOS platforms, the `FrameworkProduct` behaves just like a `LibraryProduct`, so this is mainly intended for libraries like Qt that offer a Framework on macOS and normal libraries on other platforms.

Add basic support for macOS frameworks

---

src/AutoBuild.jl
src/Products.jl
test/basic.jl
test/declarative.jl

This is an update of PR #453 with the following changes:
* Retain the `dont_dlopen` field and parameter name
* Fix a bug where instead of the library, it tried to dlopen a file with the variable name as name
* Some basic testing

Dlopen flags 2

---

src/wizard/utils.jl

Julia has a bug with `walkdir()` and symlink loops:
https://github.com/JuliaLang/julia/pull/35006

Work around symlink loop bug

---

src/Prefix.jl

Usually, we want to preserve symlinks; but in the special case of a `DirectorySource()`, it is very useful to be able to have symlinks pointing out side of the current directory and at some shared patch pool (e.g. in `GCCBootstrap@X`).  So we make the compromise that symlinks are collapsed when including `DirectorySource`'s.

Dereference symlinks when copying `DirectorySource`s

---

src/AutoBuild.jl
src/auditor/symlink_translator.jl
test/auditing.jl

This should fix issues such as the recently-diagnosed `HELICS_jll`
issues installing things on windows, where `7z.exe` decided it didn't
want to extract tarballs with deadlinks.

Add warning messages about deadlinks

---

src/auditor/symlink_translator.jl
test/auditing.jl

The current implementation shows a warning also if the link target is a relative
path to an existing file, because the check `isfile(link_target)` isn't
performed in the same directory as where the symlink is.
Addresses https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/708#issuecomment-597956747.

Fix warning about dead symlinks

---

src/AutoBuild.jl
src/Products.jl
test/basic.jl

The product can be also a `FrameworkProduct`, which doesn't have a
`dlopen_flags` field.

Fix `dlopen_flags_str`

---

src/AutoBuild.jl

- pass `-t` flag to the `ghr` command: I am not sure if it was supposed to get the token some other way. 
- make sure that the repository with the code and binary is the same when the options `deploy_bin`  and `deploy_jll` are used on their own.

Handling of github token when uploading releases

---

src/auditor/dynamic_linkage.jl

Libraries marked as "ignore" are completely ignored, and should be
things like `/lib/ld-linux.so`; e.g. things that really truly should not
be touched.  "default" libraries on the other hand, are things that we
expect to ship with julia (such as `libstdc++.so.6`).

Cleanup distinction between "default" and "ignore" libraries

---

src/AutoBuild.jl
test/basic.jl

If you specify a certain version of a package to build against, we
should ensure the same version is installed on the user's computer.

Record compat info when registering packages

---

Artifacts.toml

@vchuravy can I get you to try compiling something with this branch of BB and running it on the systems that previously didn't work?

Bump powerpc64le shards to require only glibc 2.17

---

src/auditor/symlink_translator.jl

The target of a symlink can be anything, not just a regular file

Use `ispath` to check if the target of a symlink exists

---

src/AutoBuild.jl

[This build](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=2750&view=results) found lots of dead links in `srcdir/`, but I don't think we really care about them, do we?  We are more interested in catching dead links in `destdir/`, which is the directory that will go into the tarball

Search for dead links only in destdir

---

src/auditor/dynamic_linkage.jl

We can't even ship this as part of CSL since it's not tied to compiler
version and not built by them.

Move `libc++.dylib` back to a system library

---

docs/Manifest.toml

Building the documentation is failing because of an out-of-date `Manifest.toml` file in `docs/` that doesn't know about new dependency on `LoggingExtra.jl`.

[skip ci] Update Manifest.toml of documentation

---

src/wizard/deploy.jl

We were doing this already for the `ExecutableProduct`, but not for a `LibraryProduct`

Correctly print the search path of a LibraryProduct in the wizard

---

src/wizard/utils.jl

Otherwise every future prompt would read "", potentially infinite
looping without user interaction.

Treat EOF in input as an interrupt

---

src/Auditor.jl

Exit from subprocess trying to dlopen the library, instead of returning

---

src/AutoBuild.jl

The `from_scratch` option is inaccessible from the top-level `rebuild_jll_package`, and this blocks my soon-to-be PRed Yggdrasil fix 😬

Add from_scratch option to rebuild_jll_package

---

src/wizard/obtain_source.jl
src/wizard/yggdrasil.jl

Follow-up to #747: that PR changed the return type of `get_yggdrasil()`, but in `yggdrasil_deploy` we just need the path to the local clone.  I couldn't find a method of `LibGit2.clone` taking a `GitRepo` as argument, so here I'm reverting the change to the return value of `get_yggdrasil` to simply be the path to the local clone of :deciduous_tree:

Make `get_yggdrasil` return the plain path to the local clone

---

src/Runner.jl

When trying to run CI in GitHub Actions, I got this error:
```
go: cannot find GOROOT directory: /usr/local/go1.14
```
It looks like the value of `GOROOT` comes from the host environment.  This edit
is to override a possible existing value of this environment variable.  I
determined what should have been the correct value with
```
andbox:${WORKSPACE}/srcdir # go env
[...]
GOROOT="/opt/x86_64-linux-musl/go"
[...]
```

Define `GOROOT` environment variable

---

src/wizard/obtain_source.jl
test/wizard.jl

As is it now, pressing "n" at the question whether you want to choose a
different name breaks the `while` loop, leaving `state.name` undefined.  We
should instead continue the loop if we say we want to choose a different name.
I even managed to write a test for this!

Fix warning about existing project in the wizard

---

src/Runner.jl

We need to apply the powerpc64 fix only when linking Fortran objects.  Mathieu reported this error when trying to build HiGHS for PowerPC (see https://github.com/JuliaPackaging/Yggdrasil/pull/862):
```
[ 98%] Linking Fortran executable ../bin/fortrantest
cd /workspace/srcdir/HiGHS/build/check && /usr/bin/cmake -E cmake_link_script CMakeFiles/fortrantest.dir/link.txt --verbose=false
/opt/powerpc64le-linux-gnu/bin/../lib/gcc/powerpc64le-linux-gnu/4.8.5/../../../../powerpc64le-linux-gnu/bin/ld: warning: libpthread.so.0, needed by ../lib/libhighs.so.1.0.0, not found (try using -rpath or -rpath-link)
/opt/powerpc64le-linux-gnu/bin/../lib/gcc/powerpc64le-linux-gnu/4.8.5/../../../../powerpc64le-linux-gnu/bin/ld: warning: libdl.so.2, needed by …
```

Add link only flags to the gfortran wrapper

---

Project.toml
src/AutoBuild.jl
src/Prefix.jl

I'd like to be able to keep shipping the log files in the tarball, as they are very valuable for later debugging of the build.  Compressing them should address some complaints about their large size in the artifacts directory.

Compress log files in the tarball

---

src/Products.jl
src/wizard/interactive_build.jl
test/basic.jl

This should alleviates issues like https://github.com/JuliaPackaging/Yggdrasil/pull/930#issuecomment-618997706, at least for symbols in Base -- at least for the version of Julia used to build the package.  I'm happy also to make this an error instead of a simple warning.

Throw an error if a variable name is already defined in Base

---

src/AutoBuild.jl

Simon Byrne reported that on MacOS 10.13-, setting
`DYLD_FALLBACK_LIBRARY_PATH` failed to load `libc++`, which is referred
to by `@rpath/libc++.dylib` by `libLLVM`.  This is most likely because
these older MacOSs have a default `DYLD_FALLBACK_LIBRARY_PATH` that gets
overridden, and the new value searches for `libc++.dylib`
unsuccessfully.

[JLL gen]: Set default value for `DYLD_FALLBACK_LIBRARY_PATH`

---

src/AutoBuild.jl
src/Declarative.jl
test/declarative.jl

The platform will be brought back when cleaning up the merged objects.
Also, we need to special-case `platform_key_abi("any")` in `build_tarballs()`.

Do not write platforms to JSON if building for AnyPlatform

---

Manifest.toml
Project.toml
src/wizard/interactive_build.jl

Say I build a library and then discover that it actually depends
on Zlib. At the moment, I have to go back to the start of the
wizard and declare my additional dependency. It would be nice
to just request that the wizard add it from inside the environment.
This is what this PR implements by exposing an AF_UNIX server that
responds to requests from the sandbox.
With a suitable `bb` command, the following works from inside the sandbox:
```
sandbox:${WORKSPACE}/srcdir # bb add Zlib_jll
Updating registry at `~/.julia/registries/General`
Updating git-repo `https://github.com/JuliaRegistries/General.git`
Resolving package versions...
Updating `/tmp/jl_q0IePp/mRAcrdQ3/.project/Project.toml`
[83775a58] + Zlib_jll v1.2.11+9
Updating `/tmp/jl_q0IePp/mRAcrdQ3/.project/Manifest.toml`
[83775a58] + …
```

Add "Wizard service" to modify Wizard state during interactive build

---

src/Prefix.jl

Make sure the artifacts of dependencies are downloaded, even if lazy

---

src/Prefix.jl

This doesn't fail badly if the artifact is not available for the given platform.
See https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/786#issuecomment-629863568

More robust check that artifact is installed

---

src/wizard/interactive_build.jl

This was due to the fact that when rerunning the wizard script we weren't
failing on error and the last command, `auto_install_license`, was always
successful.
See https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/779#issuecomment-625576692

Fix wizard wrongly reporting as successful failing builds

---

src/Products.jl

In `locate`, when launching an external Julia to test whether dlopen work
on a library, pass `--startup-file=no` to the subprocess to avoid any issues
with commands in a user's startup.jl file.
While I don't know a specific bug this causes, in the corresponding code in
BinaryProvider it triggered a [very annoying and difficult to debug issue](https://github.com/JuliaPackaging/BinaryProvider.jl/pull/195), so
better be safe than sorry?

Fix isolated dlopen

---

.github/workflows/documentation.yml
docs/.gitignore
docs/make.jl
docs/src/build_tips.md
docs/src/troubleshooting.md

Many users found the [Build tricks](https://github.com/JuliaPackaging/Yggdrasil/wiki/Build-Tricks) in Yggdrasil wiki hard to find, see #685.  This is understandable as that wiki page is advertised basically nowhere, apart from me spamming it on Slack.
One of the reasons why I didn't like them to be in BinaryBuilder documentation was that opening documentation pull requests here was a bit tedious as one had to go through the full CI, but #783 decoupled building of documentation from the rest of CI

[skip ci] Move build tricks from Yggdrasil wiki to BB documentation

---

src/Rootfs.jl
src/wizard/obtain_source.jl

This avoids crashing the wizard badly if the user doesn't accept the terms of
the SDK.
Fix #770

Ask to the user to accept macOS SDK during wizard

---

src/Products.jl
test/basic.jl

This allows passing both `libnames` and `dir_paths` as lone strings, as it is
done by the wizard.
Fix #813

Add new constructor for `LibProduct`

---

src/AutoBuild.jl

This should fix issues in `Git_jll` where `git` requires a particular
version of `libpcre2-8.dylib`; the changes within that libcpre are
backwards-incompatible without changing the SONAME.
In general however, we want executables within JLL packages to get as
close of a view of their build environment as possible, so we should
prioritize JLL package libraries over those sitting in Julia's libdir.

Move Julia's libdirs to the end of `LIBPATH_list` in JLL packages

---

Artifacts.toml

Associated Yggdrasil PR: https://github.com/JuliaPackaging/Yggdrasil/pull/1184

Update MacOS GCC shards to have LTO/plugin support

---

src/AutoBuild.jl

Perhaps this will fix our wizard-ignoring-errors problems.

Return proper error code in all branches of `autobuild()`

---

src/wizard/obtain_source.jl
test/wizard.jl

This avoids issues like https://github.com/JuliaPackaging/Yggdrasil/pull/1266

Automatically remove `_jll` from name of project in Wizard

---

src/AutoBuild.jl
test/jll.jl

Happy to receive better suggestions for the name of the function.
TODO:
CC: @fingolfin

Add to the JLLs a function to tell whether the current platform is supported

---

src/AutoBuild.jl
src/wizard/deploy.jl
src/wizard/utils.jl
test/basic.jl

I am playing around with BinaryBuilder and private repos. Specifically, trying to update an existing _private_ jll repo. The `git fetch` step here asks for username & password, even though I am using `ENV["GITHUB_TOKEN"]`.
Passing the credentials to `fetch` (like is done for `clone` just a few lines before) would make sense to me. It seems to fix it for my use-case, but I haven't tested it beyond that.

Pass credentials to Libgit2.fetch in init_jll_package

---

docs/src/FAQ.md
docs/src/reference.md
src/AutoBuild.jl

Moves the `build_tarballs` docstring a bit down in the manual and puts the `--help` text right after it. It will render as a code block, so unfortunately won't be searchable, but still better than not having it at all I think.

Include build_tarballs --help text in the manual

---

docs/src/building.md
docs/src/jll.md
src/AutoBuild.jl

This adds two new capabilities:
* `--deploy=local`; for those who really just want to test out their new
JLLs locally, this makes it a cinch.  Just tack `--deploy=local` onto
the end of your `build_tarballs.jl` invocation, and you'll get the
artifacts installed and the JLL packages built within your
`~/.julia/dev` directory. (Note that you will still need to add that
directory into any environment you want to use it from)
* `override` directories for `dev`'ed out JLL packages.  This allows a
user to override the binaries within a JLL easily and cheaply.  At
compile time, the JLL package will look for an `override` directory in
its project root, and if it finds it, it will attempt to load binaries
from there instead of from an Artifact.  To aid in setting this up, JLLs
now have a …

Improve local development workflow

---

src/AutoBuild.jl
test/declarative.jl
test/jll.jl

The two new functions have similar but not identical signature; this change
means that we don't have to pass things to autobuild() which are not needed
for building, but rather just for the meta JSON; and vice versa.
I came up with this while trying to write a patch for issue #856, and trying to understand what data I need to pass where.
The big diff in `test` is mostly due to the removal of `mktempdir() do ... end` blocks; if one uses the "ignore whitespace" diff mode, one can see the actual (comparatively small) changes.

Move part of autobuild() into new get_meta_json() helper

---

src/AutoBuild.jl

Oops, I screwed up in PR #872 -- this hopefully fixes it. I only noticed it when I wanted to add a `julia_dependencies` kwarg... I hope I got it right now. It's a bit frightening that there is no test for `build_tarballs()` in there at all, though... Perhaps at least the variant with `--meta-json` could be tested, which likely would have caught this one?
I also wonder if perhaps @staticfloat's work in #861 can be used to test (in the test suite) the generation of a full JLL, locally, by outputting it into a temporary directory; and then perhaps `diff` could be used to compare it to a pregenerated copy, so that any changes are detected. (Of course one could then also repeat this with different settings used).

build_tarballs: fix call to get_meta_json

---

src/Wizard.jl

`Wizard.jl` did not import `JSON` package, failing at successfully obtaining token:
```
ERROR: LoadError: UndefVarError: JSON not defined
Stacktrace:
[1] obtain_token(; ins::Base.TTY, outs::Base.TTY, github_api::GitHub.GitHubWebAPI) at /home/pxl_th/.julia/dev/BinaryBuilder/src/wizard/github.jl:89
[2] obtain_token() at /home/pxl_th/.julia/dev/BinaryBuilder/src/wizard/github.jl:31
[3] github_auth(; allow_anonymous::Bool) at /home/pxl_th/.julia/dev/BinaryBuilder/src/wizard/github.jl:18
[4] init_jll_package(::String, ::String, ::SubString{String}) at /home/pxl_th/.julia/dev/BinaryBuilder/src/AutoBuild.jl:828
[5] build_tarballs(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any; kwargs::Any) at /home/pxl_th/.julia/dev/BinaryBuilder/src/AutoBuild.jl:195
[6] top-level scope at …
```

Import JSON in Wizard

---

src/AutoBuild.jl

This reverts commit bfb4675ac4e09acc0579177b5072f8d2ec764c71.  See https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/880#discussion_r469504976.

Revert "Move init of path lists in JLLs to precompile time (#844)"

---

.travis.yml
Manifest.toml
Project.toml
src/AutoBuild.jl
src/auditor/dynamic_linkage.jl
src/wizard/interactive_build.jl
test/basic.jl
test/building.jl
test/runtests.jl

This PR also fixes a whole bunch of testing issues.
This version includes the new RootFS and PlatformSupport shards, which bundles new versions of musl, glibc, the macos SDK, and includes a RootFS that is based on Alpine 3.12.
Closes #893

Bump RootFS

---

src/AutoBuild.jl
test/basic.jl

Resolves #856
I ended up using a plain string for the `julia_compat` argument, which is written unchanged into the `Project.toml` (however, it gets validated before, so the user can't insert invalid version specifiers). My first prototype used `Pkg.Types.VersionSpec`, but I moved away from that for several reasons:
1. As far as I can tell, `Pkg.Types.VersionSpec` is completely undocumented
2. Julia package developers are used to compat strings like `"~1.4"`; but they can't use that directly with `Pkg.Types.VersionSpec`; not everybody will now (or find intuitive) that  "~1.4" needs to be entered as `"1.4.0 - 1.4"`, or `"^1.4"` as `"1.4.0 - 1"`
3. One can ease this by using `Pkg.Types.semver_spec` but again that's completely undocumented (I still use it in this PR to validate the version …

Add julia_compat keyword argument to build_tarballs

---

src/Wizard.jl
src/wizard/deploy.jl

We can make the `bb add` smarter and get also the UUID of the package, but I
think this check is good regardless of that improvement.
Ref #818.

Do not write UUID of packages without UUID in wizard script

---

src/AutoBuild.jl
test/jll.jl

Changing JLL generation to use the new 1.6 `Artifacts` stdlib, instead of Pkg, and optimizing things to do more work at compile time.

WIP 1.6 Artifacts JLL generation

---

src/wizard/interactive_build.jl

This way, things don't error if an existing dependency needs to
change version or otherwise get updated. Fixes #821

In `bb add` command, clear artifacts directory before adding a new dep

---

src/AutoBuild.jl

This should address the issue where the local repository already exists but it
doesn't know about the refspec `main`.

Fetch remote repository before pushing to it

---

src/AutoBuild.jl
test/basic.jl

Without this change we have the following behaviour (using the `exactly_this_version` function from `AutoBuild.jl`):
```julia
julia> exactly_this_version(VersionSpec("8.3"))
"=8.3"
julia> exactly_this_version(VersionSpec("8.3.0-8.3"))
"=8.3"
julia> exactly_this_version(VersionSpec("8.3.1-8.3"))
"8.3.1-8.3"
```
Similarly `8.0-8` or `8` returns `=8` instead if just `8`.
In these cases the lower bound equals the upper bound but not all three version components are fixed.
I tried looking into Pkg.jl (`src/versions.jl`) but could not think of any way to do this without accessing that field directly.

compat bounds: fix version range test for 'x.y.0-x.y'

---

src/Auditor.jl
src/auditor/compiler_abi.jl

In addition to `libgomp`, it's possible that a library links against libatomic,
so we need to check also that one.

Teach audit to check multiple CSL libraries

---

docs/src/troubleshooting.md

It looks like the parsing rule is not documented, and the implementation may change from releases to releases, so better to mention this function in doc.

Mention `parse_dl_name_version` in Troubleshooting

---

src/auditor/compiler_abi.jl
test/auditing.jl

Audit currently doesn't complain if there is a mismatch between the libgfortran
version of the target platform and the one linked by the product.

[Audit] Make sure we're linking to expected libgfortran version

---

test/declarative.jl

This removes the need to hardcode some lowlevel implementation
details of BBB here, which makes it possible to change those.

Remove some tests that belong into BinaryBuilderBase

---

src/BinaryBuilder.jl

This is useful in the same way as libc, arch, etc. are.
See https://github.com/JuliaPackaging/Yggdrasil/pull/2323#discussion_r549897586

Re-export nbits() from BinaryBuilderBase

---

Manifest.toml
docs/src/troubleshooting.md

This includes https://github.com/JuliaPackaging/BinaryBuilderBase.jl/commit/b33bde58330f7bea87f150de444961758be685e8, which improves the docstrings of the products, making redundant the tip in the troubleshooting section about parsing the name of the libraries.

Update BinaryBuilderBase in the manifest

---

Manifest.toml
azure-pipelines.yml
src/AutoBuild.jl
test/basic.jl
test/jll.jl

Because of https://github.com/JuliaPackaging/JLLWrappers.jl/pull/24 and
https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/90, we need to bump
the compat version of `JLLWrappers.jl`.

[AutoBuild] Increase compat of JLLWrappers to v1.2.0

---

src/auditor/extra_checks.jl
test/auditing.jl

A binary is accpetable for this platform also if it doesn't specify any float
ABI.
Ref: https://github.com/JuliaPackaging/Yggdrasil/pull/2455.

[Auditor] Improve check for amv7l float ABI

---

src/Wizard.jl

[Wizard] Fix name of `save_wizard_state`

---

src/wizard/github.jl

Example of the original output:
```
Authenticating with GitHub
To continue, we need to authenticate you with GitHub. Please navigate to
the following page in your browser and enter the code below:
https://github.com/login/device
#############
#############
Successfully obtained GitHub authorization token!
This token will be used for the rest of this BB session.
You will have to re-authenticate for any future session.
However, if you wish to bypass this step, you may create a
personal access token athttps://github.com/settings/tokens
and add the token to the
~/.julia/config/startup.jl file as:
ENV["GITHUB_TOKEN"] = <token>
This token is sensitive, so only do this in a computing environment you trust.
```

Add space before github tokens URL

---

Manifest.toml
Project.toml
azure-pipelines.yml
test/wizard.jl

In
https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/937c7af962af6745809eb3edaca201b88f1ddc3e/test/wizard.jl#L48-L57
we create a tarball, compute its hash and serve it via HTTP, for use during the tests.  The wizard functions in the tests would download this file, compute the hash and compare with the hash of the original file.  The problem is that we're often observing that the hash of the original file is different from that of the downloaded files, causing a failure in the tests.
Switching to `Tar.jl` to create the tarballs works around #987.

Use `Tar.jl` to create tarball to use for Wizard tests

---

Manifest.toml
src/AutoBuild.jl
test/basic.jl
test/jll.jl

... using the optional meta data provided by users in BBB's Dependency type.
This is companion to PR https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/123, and part of a new effort to address https://github.com/JuliaPackaging/BinaryBuilderBase.jl/issues/89. My previous attempt, https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/98, was not sufficient, as it failed to address the core issue: that while a compat string can be turned into a VersionSpec, the reverse is in general not possible; so specifying the compat bounds using a VersionSpec isn't too useful. The solution chosen here is to instead simply store it as a string (validated by calling `semver_spec` on it).
Unfortunately, this change is completely untested! The reason is that I am not sure at this point how I …

Produce compat entries in Project.toml

---

docs/src/jll.md

Mention the new recommended (and thread-safe) syntax to call the function
wrapper.

[Docs] Improve documentation of `ExecutableProduct` wrappers

---

src/AutoBuild.jl

Remove verbose from the `@info` calls about deployment location (seems desirable without verbose). Add a local specific deploy message pointing to `code_dir`. Resolve #1039

Added local build directory @info

---

Manifest.toml
Project.toml
src/AutoBuild.jl
src/wizard/interactive_build.jl

Use the extra `platform` argument introduced in PR https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/135
This will of course fail until that PR is merged.

Add platform argument to cleanup_dependencies

---

src/wizard/deploy.jl

Small step towards making it easier to build packages for the new platforms.

[Wizard] Require Julia v1.6 for the JLL package generated by the recipe

---

Manifest.toml
test/building.jl

This is a long standing issue, I suggest to skip the test for the time being so
at least our CI can get back to work.  I opened issue #1053 to track the bug.

Skip testing of broken FreeBSD toolchain with libgfortran 3

---

codecov.yml

Okay, I think this accomplishes what you want. Here's an explanation of what it does.
There will be three Codecov statuses:
- `codecov/minimum`
- `codecov/project`
- `codecov/patch`
If, on the PR merge commit, the total coverage of the entire BinaryBuilder.jl package is greater than or equal to `50%`, this status will pass. Otherwise, it will fail.
Let `M` denote the total coverage of the entire BinaryBuilder.jl package on the `master` branch. For example, here is the current value of `M`:
[![codecov.io](http://codecov.io/github/JuliaPackaging/BinaryBuilder.jl/coverage.svg?branch=master)](http://codecov.io/github/JuliaPackaging/BinaryBuilder.jl?branch=master)
If, on the PR merge commit, the total coverage of the entire BinaryBuilder package is greater than or equal to `M - 3%`, this …

Improve the Codecov configuration

---

src/AutoBuild.jl
test/jll.jl

Hi!
This adds a mention to the Yggdrasil committer when deploying creating PRs to the registry.
This fails silently because some commits can have no github author if the email address used for the commit doesn't match any GitHub user.
Closes #1056

Ping the Yggdrasil committer when deploying

---

.github/workflows/documentation.yml
Manifest.toml
Project.toml
src/Auditor.jl
src/AutoBuild.jl
src/auditor/codesigning.jl
src/auditor/dynamic_linkage.jl
src/auditor/soname_matching.jl

This avoids clash between log files of different packages when mounting all of
them together for a build.
Companion pull request in `BinaryBuilderBase`: https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/146

Save log files to `logdir(prefix; subdir=src_name)`

---

docs/src/building.md

Stress that the fact dependencies expand C++ string ABI/libgfortran version
doesn't influence the current build.

More improvements to docs

---

src/wizard/github.jl
src/wizard/utils.jl

This seems like the best way to catch the error. Should I be checking if it's actually an auth error?

Catch error from stale GitHub token

---

docs/src/build_tips.md

This variable has been removed in
https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/149 because it
wasn't really useful.

[docs] Remove reference to `OBJC` environment variable

---

Manifest.toml
Project.toml

This allows both BinaryBuilderBase 0.6 and 1.0 but updates the manifest to use 1.0. Allowing both means we should be able to make a non-breaking release. I've changed the Project.toml version accordingly in a separate commit.

Update to BinaryBuilderBase 1.0

---

src/AutoBuild.jl
src/wizard/state.jl

We no longer use Travis anywhere, let's remove dead codepaths.

Remove some old references to Travis

---

src/AutoBuild.jl

By moving this check earlier, we avoid bad surprises after a potentially long
compilation.
Fix ##1108.  CC: @eschnett

[AutoBuild] Check validity of package name directly in `build_tarballs`

---

Project.toml
src/AutoBuild.jl

Output example when building Lua:
```
[ Info: Timings: setup: 16.79s, build: 2.0s, audit: 10.87s, packaging: 0.88s
```
Fix #1111.

[AutoBuild] Add timings of different steps

---

docs/src/build_tips.md

We may eventually want to add Go and Rust hints to the wizard, but at the moment we don't support those toolchains at all in that environment.

[Docs] Add installation tips about Rust and Go

---

src/auditor/instruction_set.jl

Running this on the product from OpenBlas in yggdrasil takes this part from 
```
5.385089 seconds (48.11 M allocations: 4.965 GiB, 11.82% gc time)
```
to
```
1.505047 seconds (13.24 M allocations: 1.082 GiB, 8.13% gc time)
```
It is still not super significant because running the ´objdump` above takes like 15 seconds, but it is a start.

improve performance of instruction set checker

---

src/auditor/compiler_abi.jl
src/auditor/instruction_set.jl

We we relying on the fact that when doing
```julia
run_interactive(...; stdout=IOBuffer())
```
the exit status of the command would be accidentally ignored, now fixed in
`BinaryBuilderBase`.  With this change we ensure that the exit status is always
ignored.

[Audit] Ignore status of some audit processes

---

src/wizard/obtain_source.jl
test/wizard.jl

This PR modifies the step in the wizard that modifies file names if duplicated file names exist when downloading sources.
If the files have multiple extensions like `blahh.tar.gz`, `splitext` doesn't split enough and you end up with `foobar.tar_n.gz` which doesn't match [the list of extensions we check against](https://github.com/JuliaPackaging/BinaryBuilderBase.jl/blob/eb8ade82382394ca54a05dc9e7bb27cf2e5ba050/src/Sources.jl#L38-L39). With this, you should now end up with `foobar_n.tar.gz`
closes #1092

modify check for existing files that properly splits name and extension

---

src/wizard/deploy.jl

This PR adds a sort step to order the tuple of products before writing out in the `deploy` step. This uses `rev=true` so that the order would be `LibraryProduct`, `FrameworkProduct`, `ExecutableProduct`. 
I thought this was handling an `Product[]` directly behind the scenes, but it's just writing the brackets and names as strings, so I had to use tuple sort instead.
Should close #1109

[wizard] add sort step to products array writing

---

Project.toml
src/AutoBuild.jl

Unless I'm missing something, this argument isn't used anywhere?  It looks like it was used until #536

[AutoBuild] Remove unused argument from `init_jll_package`

---

Manifest.toml
Project.toml

Deprecation warnings from Github.jl dependencies were polluting build logs, this fixes the issue
See https://github.com/JuliaWeb/GitHub.jl/pull/191

Update Github.jl to min ver 5.7.2

---

src/AutoBuild.jl
test/basic.jl

Supersedes https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1152
Resolves #1149
If *.log files are present, yields:
```bash
┌ Warning: Build failed, the following log files were generated:
│   - ${WORKSPACE}/srcdir/wget-1.21.1/config.log
│ 
│ Launching debug shell:
└ @ BinaryBuilder ~/.julia/dev/BinaryBuilder/src/AutoBuild.jl:822
```
Otherwise (in case of no log files), no change from current version.

[Autobuild] Add log file prompt

---

README.md
docs/src/build_tips.md
docs/src/troubleshooting.md
src/AutoBuild.jl

This was changed deprecated in Documenter.jl 0.20.0 and dropped in 0.24.0

README.md: update latest -> dev in doc URLs

---

Manifest.toml
Project.toml

@jeremiahpslewis this is perhaps what you wanted to do the other day?  Without
changing the compat bounds in #1168, `ghr_jll` wasn't even touched at all.  BTW,
here we don't test the upload stage, so just running the tests with this still
doesn't ensure anything.

Allow `ghr_jll` v0.14

---

src/Auditor.jl
src/auditor/dynamic_linkage.jl

Our audit logs contain lots of references to system libraries.  I've been
meaning to do this for a long time, I'll probably keep this open for some more
time to collect more libraries we spot into the wild, but I wanted to open this
PR to make sure this is a good idea.  CC: @staticfloat

[Auditor] Add more ignored libraries

---

src/AutoBuild.jl
test/basic.jl

Companion to https://github.com/JuliaPackaging/JLLWrappers.jl/pull/35

Support augment_platform in BB

---

src/auditor/dynamic_linkage.jl
test/auditing.jl

Came up in https://github.com/JuliaPackaging/Yggdrasil/pull/3648

[Auditor] Fix path normalisation for rpaths

---

src/wizard/obtain_source.jl

We don't really want to create things called `file.zip?raw=true`,
especially as that may screw up our Archive detection later on.

Strip URL parameters from names on disk

---

src/AutoBuild.jl

This adds the following to the help output for quick reference:
```
Supported Platforms:
i686-linux-gnu
x86_64-linux-gnu
aarch64-linux-gnu
armv6l-linux-gnueabihf
armv7l-linux-gnueabihf
powerpc64le-linux-gnu
i686-linux-musl
x86_64-linux-musl
aarch64-linux-musl
armv6l-linux-musleabihf
armv7l-linux-musleabihf
x86_64-apple-darwin
aarch64-apple-darwin
x86_64-unknown-freebsd
i686-w64-mingw32
x86_64-w64-mingw32
```

list supported triplets in --help

---

src/AutoBuild.jl
test/building.jl

As a matter of fact Pkg doesn't like them, I think it's better to automatically
error our instead of having to tell users that they shouldn't use them.
Recent cases on Yggdrasil: https://github.com/JuliaPackaging/Yggdrasil/pull/5345#discussion_r953729854 and https://github.com/JuliaPackaging/Yggdrasil/pull/5344#discussion_r953604740.

[AutoBuild] Disallow prerelease numbers in versions of JLLs

---

Manifest.toml
Project.toml
src/AutoBuild.jl
test/building.jl

Long term plan is still to do #778, but that's a lot of work, and we have little time at the moment.  Simply splitting the logs into a separate tarball, instead, is a simpler short-term solution which has some very important bonuses:
- the git tree hash of the main tarball should be reproducible (as long as you use the same toolchain)
- which means we can start testing reproducibility of builds
- rebuilding a package without changing its content won't create a new artifact: less strain on the Package Storage Server.
I still need to do tests about deployment on Yggdrasil though (***Edit***: see https://github.com/JuliaPackaging/Yggdrasil/pull/5526).

[AutoBuild] Split log files into a separate tarball

---

Manifest.toml
Project.toml
src/AutoBuild.jl
test/jll.jl

Companion PR to https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/275

Load top-level dependencies in the main source file

---

docs/make.jl
docs/src/index.md

https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/268, https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/270, and #1229 made it easier to investigate our reproducibility capabilities, and I think we are at a place where we can start talking about them.
Side note, in Yggdrasil we've had a [reproducibility scanning tool](https://github.com/JuliaPackaging/Yggdrasil/blob/0b127481fd158ef78b54283b39634831206da3e8/reproducibility_scanning_tools.jl) for over two years and the very few times I used it I always found reproducible builds, but it was a bit annoying to use as it had to extract the content of the tarballs: now instead we can directly look at the SHA256 sum, or the git tree hash.  But this also gives you an idea of how long our builds have been reproducible in …

[docs] Add section about reproducibility

---

Manifest.toml
Project.toml
test/building.jl

They changed because of the change of the value of `-Wl,-sdk_version` in BinaryBuilderBase: https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/284

Fix expected hash of macOS builds

---

azure-pipelines.yml
src/Auditor.jl
src/auditor/extra_checks.jl
test/auditing.jl

This should ensure reproducibility of import libraries.  Fix #1245
I'm sure the replacement could be done in a somewhat nicer way by working with the raw bytes, but the regexp replacement is so simple.

[Auditor] Add a pass to normalise timestamps in Windows import libraries

---

Manifest.toml
src/AutoBuild.jl
test/basic.jl
test/jll.jl

Second part for fixing https://github.com/JuliaPackaging/Yggdrasil/pull/6417#issuecomment-1476823499.
I believe this needs https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/304 to pass all tests, but this PR reduces the need to convert  `RuntimeDependency` -> `Dependency`.

[AutoBuild] Do not convert `RuntimeDependency` -> `Dependency` unnecessarily

---

docs/src/building.md
src/AutoBuild.jl

Fixes #1274.
I don't know if this feature is even desired, but for me it is sometimes super helpful to have when testing build chains with multiple, non-registered JLLs locally.

Add `--skip-build` flag to allow deploying prebuilt tarballs

---

docs/src/build_tips.md

This change adds a note about where to find Meson GCC toolchain files.
When I first read this section as-is, I assumed that CMake was the only build system with GCC-specific toolchain files which led to a fruitless effort to make `CC=gcc CXX=g++ meson` work.

Add note about Meson GCC toolchain to `build_tips.md`

---

docs/Project.toml

Hopefully a simple way to get the docs builds fixed (e.g. https://github.com/JuliaPackaging/BinaryBuilder.jl/actions/runs/6266351818/job/17017134146?pr=1295)
At some point it would be good to get the docs upgraded to 1.0, but this is a quick stop-gap.

docs: add version bound for Documenter

---

src/AutoBuild.jl

The username might not be available if authenticating as a GitHub App. Also, when authenticating with a token, the username isn't necessary.

Don't request username in init_jll_package

---

src/AutoBuild.jl
src/wizard/deploy.jl

This is a followup to https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1304 since there were two more authentications that relied on querying the potentially non-existent GitHub username. 
The second commit might not be the right approach but it allowed me to build new binaries while authenticating as a GitHub app. The issue is that https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/ad70f55fb09aeb13324e4e69bf2c6df4b4e2fc4c/src/AutoBuild.jl#L1589 ends up querying username information from the local git repo when calling https://github.com/JuliaLang/julia/blob/187e8c2222878c68b2afc9295ab8dc61773bd7f2/stdlib/LibGit2/src/signature.jl#L66-L72.

Don't query GitHub username and use dummy credentials when committing

---

src/wizard/github.jl

Losing-up the check on token size to allow for new protocol.
Fix #1281.

allowing use of fine-grained tokens

---

src/AutoBuild.jl

When uploading a large number of artifacts, like with Enzyme, we've observed errors in `ghr` like
```
Failed to upload one of assets: one of the goroutines failed: failed to upload asset: /tmp/jl_tLeFr2/Enzyme-logs.v0.0.128.i686-linux-gnu-cxx11-llvm_version+15.tar.gz: failed to upload release asset: /tmp/jl_tLeFr2/Enzyme-logs.v0.0.128.i686-linux-gnu-cxx11-llvm_version+15.tar.gz: POST https://uploads.github.com/repos/JuliaBinaryWrappers/Enzyme_jll.jl/releases/163097283/assets?name=Enzyme-logs.v0.0.128.i686-linux-gnu-cxx11-llvm_version%2B15.tar.gz: 403 You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
```
Passing the `-p` option to reduce parallelism is an attempt to avoid this issue.
CC: @wsmoses.

[AutoBuild] Allow limiting concurrency of `ghr` uploads

---

Project.toml
src/AutoBuild.jl
test/building.jl

Validation of the field that will determine the name of the generated JLL package is what you want 99.9% of the time. But that other 0.1% of the time is `Yggdrasil/0_RootFS/PlatformSupport/build_tarballs.jl`: each invocation of the script specifies a separate platform, the triplet of which gets embedded in the name. Unfortunately e.g. `PlatformSupport-x86_64-unknown-freebsd13.2` is not a valid identifier, so building PlatformSupport with recent BinaryBuilder fails.

Allow disabling the `isidentifier` check in `build_tarballs`

---

src/Auditor.jl
test/auditing.jl
test/build_tests/libfoo/CMakeLists.txt
test/build_tests/libfoo/Makefile.am
test/build_tests/libfoo/libfoo.pc
test/build_tests/libfoo/meson.build

Solves #1338, but I haven't tested this.
Ping @giordano.

Make pkg-config files relocatable post-installation

---

src/Auditor.jl
test/build_tests/libfoo/libfoo.pc

Addresses https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1346#issuecomment-2525952991

Extend pkgconfig relocatization to cover `exec_prefix` too.

---

src/AutoBuild.jl

https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1355#issuecomment-2560299221

[AutoBuild] Don't allow building for riscv64 for old Julia

---

Project.toml
src/AutoBuild.jl
test/basic.jl
test/building.jl
test/jll.jl

This is necessary to include https://github.com/JuliaPackaging/JLLWrappers.jl/pull/74, which allows loading JLL packages with unknown platforms.
This will be mildly disruptive because compat bounds will change and CI checks in the General registry won't like them, I suggest we resolve conflicts in the General registry (users installing such packages will likely upgrade to JLLWrappers v1.7 anyway).  I considered the option of changing the compat bound only if `riscv64` is among the architectures of the platforms in the new build, but
* the list of platforms isn't currently passed to `register_jll`, we could change that, but it's a a bit of a churn
* doing that wouldn't even be sufficient to avoid all issues in the registry, as we'll still likely publish new builds for many packages for the …

[AutoBuild] Always require JLLWrappers v1.7.0

---

Project.toml
docs/src/build_tips.md
src/AutoBuild.jl

Companion PR to https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/399 to allow passing the keyword arguments through to the underlying shard selector.

Pass through the new Rust and Go version arguments

---

src/AutoBuild.jl
test/jll.jl

Should remedy issues seen with registration of ONNXRuntime_CUDA (using the `cuda_platform` platform tag, e.g., `cuda_platform="jetson"`) in https://github.com/JuliaPackaging/Yggdrasil/pull/10426, and investigated in https://github.com/JuliaPackaging/Yggdrasil/pull/10476 .

[AutoBuild] Replaced platform triplet string comparison with platform comparison in rebuild_jll_package

---

src/auditor/dynamic_linkage.jl
src/auditor/extra_checks.jl
test/auditing.jl

Currently the auditor is only checking for the correct OS/ABI and producing a warning on FreeBSD when it doesn't match. This warning is incorrect on AArch64 though, as FreeBSD instead uses an ELF note to declare the OS/ABI. The change implemented here looks for such a note when the OS/ABI in the ELF header is NONE.
~~Note that there are no tests added... I'd be interested in any suggestions for how best to test this given that the functions I modified are not currently tested, at least directly (AFAICT).~~

Check for a branded ELF note when OS/ABI is NONE

---

docs/src/jll.md

Emphasize more strongly that the first form should be preferred,
the second form is only there for people who really must support
Julia before 1.6.

Rephrase the ExecutableProduct documentation

---

src/AutoBuild.jl

@maleadt removed augmentation recently from pocl_jll 
https://github.com/JuliaBinaryWrappers/pocl_jll.jl/commit/cfcdb23a62c76e835704c047753a0a69dae9e041
But the `.pkg` dir remained confusing things down the road.

Remove `.pkg` if no longer augmenting

---

test/auditing.jl

The official `1.7.3` version of `julia` for the `x86_64-linux-gnu` triplet ships with `libgfortran.so.4`:
```julia
julia> VERSION
v"1.7.3"
julia> using Libdl
julia> foreach(println, Libdl.dllist())
linux-vdso.so.1
/lib/x86_64-linux-gnu/libdl.so.2
/lib/x86_64-linux-gnu/libpthread.so.0
/lib/x86_64-linux-gnu/libc.so.6
[...]/bin/../lib/libjulia.so.1
/lib64/ld-linux-x86-64.so.2
[...]/bin/../lib/julia/libgcc_s.so.1
[...]/bin/../lib/julia/libopenlibm.so
[...]/bin/../lib/julia/libjulia-internal.so.1
[...]/bin/../lib/julia/libunwind.so.8
[...]/bin/../lib/julia/libLLVM-12jl.so
/lib/x86_64-linux-gnu/librt.so.1
[...]/bin/../lib/julia/libatomic.so.1
[...]/bin/../lib/julia/libstdc++.so.6
/lib/x86_64-linux-gnu/libm.so.6
[...]/bin/../lib/julia/libz.so.1
[...]/lib/julia/sys.so …
```

fix `libgfortran` version in auditor test

---

test/runtests.jl

I've had a look at https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/1377, and I couldn't easily find where the `sudo` prompt cmd was ran (it took me some time to find that it was defined in `BinaryBuilderBase`) and also the first tests using it in `basic.jl` are hiding valuable stdout/err output, so I thought it would be a good idea to print some information about preferred sunner and privileges as soon as possible in the test suite.
This is what the test suite output looks like after this PR:
```
Testing Running tests...
[ Info: Julia versioninfo():
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
OS: Linux (x86_64-pc-linux-gnu)
CPU: 12th Gen Intel(R) Core(TM) i7-12700H
WORD_SIZE: 64
LIBM: libopenlibm
LLVM: libLLVM-12.0.1 (ORCJIT, goldmont)
[ Info: …
```

print some context info for privileges in test suite

---

Project.toml
test/auditing.jl
test/building.jl

BinaryBuilderBase v1.40.0 introduced [a change in the compiler wrappers](https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/435) which affects the content of the generated binary files.

Update expected SHAs of tarballs
